<link rel="stylesheet" href="/css/powered.css" type="text/css" />
<div class="d3up-powered">
	<table class="stats-table">
	  <tr>
			<td>
				<img class='class-icon' src="/images/<?= $this->record->class ?>.png"/>
			</td>
			<td>
				<h1><?= $this->record->name ?></h1>
				<h3>
					L<?= $this->record->level ?> (<?= $this->record->paragon ?>) 
					<?= ($this->record->hardcore) ? "<span class='neg'>HC</span>" : "<span class='pos'>SC</span>" ?>		
					<?= ucwords(str_replace("-", " ", $this->record->class)) ?>
					<? if($this->record->_characterRg): ?>
						(<?= $this->regionDisplay($this->record->_characterRg, 'short') ?>)
					<? endif ?>
				</h3>
			</td>
		</tr>
	</table>
	<ul class="skills">
		<? foreach($this->record->actives as $active): ?>
			<?
				list($skill, $rune) = explode("~", $active);
			?>
			<li>
				<img class="skill-icon" src="/images/icons/<?= $this->record->class ?>-<?= $skill ?>.png">
			</li>
		<? endforeach ?>
		<? foreach($this->record->passives as $passive): ?>
			<li>
				<img class="skill-icon" src="/images/icons/<?= $this->record->class ?>-<?= $passive ?>.png">
			</li>
		<? endforeach ?>
	</ul>
	<table class="stats-table">
	  <tr>
	    <td class="hl-dps">
	      <div class="item-stat">
	        <span data-value="dps" class="value"><?= $this->prettyStat($this->record->stats['dps'], 0) ?></span>
	        <span class="stat">DPS</span>
	      </div>
	    </td>
	    <td class="hl-stat">
	      <div class="item-stat">
	        <span data-value="dps" class="value"><?= $this->record->stats['critical-hit'] ?: 0 ?>%</span>
	        <span class="stat">Crit</span>
	      </div>
	    </td>
	    <td class="hl-stat">
	      <div class="item-stat">
	        <span data-value="ehp" class="value"><?= $this->record->stats['critical-hit-damage'] ?: 0 ?>%</span>
	        <span class="stat">CritDmg</span>
	      </div>
	    </td>
	    <td class="hl-stat">
	      <div class="item-stat">
	        <span data-value="dps" class="value"><?= $this->record->stats['attack-speed-incs'] ?: 0 ?>%</span>
	        <span class="stat">IAS</span>
	      </div>
	    </td>
	    <td class="hl-ehp">
	      <div class="item-stat">
	        <span data-value="ehp" class="value"><?= $this->prettyStat($this->record->stats['ehp'], 0) ?></span>
	        <span class="stat">EHP</span>
	      </div>
	    </td>
	
	  </tr>
	</table>
</div>