<link rel="stylesheet" href="/css/powered.css" type="text/css" />
<div class="d3up-powered">
	<h1><?= $this->record->name ?></h1>
	<h3>Level <?= $this->record->level ?>, Paragon Level <?= $this->record->paragon ?></h3>
	<h5>
		<?= ($this->record->hardcore) ? "<span class='neg'>Hardcore</span>" : "<span class='pos'>Softcore</span>" ?>
		<?= ucwords(str_replace("-", " ", $this->record->class)) ?> Build
		<? if($this->record->_characterRg): ?>
			(<?= $this->regionDisplay($this->record->_characterRg) ?>)
		<? endif ?>
	</h5>
	<table class="stats-table">
	  <tr>
	    <td class="hl-dps">
	      <div class="item-stat">
	        <span data-value="dps" class="value"><?= round($this->record->stats['dps'], 2) ?></span>
	        <span class="stat">DPS</span>
	      </div>
	    </td>
	    <td class="hl-ehp">
	      <div class="item-stat">
	        <span data-value="ehp" class="value"><?= round($this->record->stats['ehp'], 2) ?></span>
	        <span class="stat">EHP</span>
	      </div>
	    </td>
	  </tr>
	</table>
	<ul class="skills">
		<? foreach($this->record->actives as $active): ?>
			<?
				list($skill, $rune) = explode("~", $active);
			?>
			<li>
				<img class="skill-icon" src="/images/icons/<?= $this->record->class ?>-<?= $skill ?>.png">
			</li>
		<? endforeach ?>
		<? foreach($this->record->passives as $passive): ?>
			<li>
				<img class="skill-icon" src="/images/icons/<?= $this->record->class ?>-<?= $passive ?>.png">
			</li>
		<? endforeach ?>
	</ul>
</div>