
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-bash.png http://d3db.com/static/gameasset/22/Barbarian_Bash_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-hammer-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_HammerOfTheAncients_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-cleave.png http://d3db.com/static/gameasset/22/Barbarian_Cleave_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-ground-stomp.png http://d3db.com/static/gameasset/22/Barbarian_GroundStomp_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-rend.png http://d3db.com/static/gameasset/22/Barbarian_Rend_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-leap.png http://d3db.com/static/gameasset/22/Barbarian_LeapAttack_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-ancient-spear.png http://d3db.com/static/gameasset/22/Barbarian_AncientSpear_Normal.png
wget -O barbarian-pound-of-flesh.png http://d3db.com/static/gameasset/22/Traits_Barbarian_PoundOfFlesh_Normal.png
wget -O barbarian-ruthless.png http://d3db.com/static/gameasset/22/Traits_Common_Weakspot_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-frenzy.png http://d3db.com/static/gameasset/22/Barbarian_Frenzy_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-seismic-slam.png http://d3db.com/static/gameasset/22/Barbarian_SeismicSlam_Normal.png
wget -O barbarian-nerves-of-steel.png http://d3db.com/static/gameasset/22/Traits_Barbarian_NervesOfSteel_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-revenge.png http://d3db.com/static/gameasset/22/Barbarian_Revenge_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapon-throw.png http://d3db.com/static/gameasset/22/Barbarian_WeaponThrow_Normal.png
wget -O barbarian-weapons-master.png http://d3db.com/static/gameasset/22/Traits_Barbarian_ThunderousBlows_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-sprint.png http://d3db.com/static/gameasset/22/Barbarian_Sprint_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-threatening-shout.png http://d3db.com/static/gameasset/22/Barbarian_ThreateningShout_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-earthquake.png http://d3db.com/static/gameasset/22/Barbarian_Earthquake_Normal.png
wget -O barbarian-inspiring-presence.png http://d3db.com/static/gameasset/22/Traits_Barbarian_InnerRage_Normal.png
wget -O barbarian-berserker-rage.png http://d3db.com/static/gameasset/22/Traits_Barbarian_Slaughter_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-whirlwind.png http://d3db.com/static/gameasset/22/Barbarian_Whirlwind_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-furious-charge.png http://d3db.com/static/gameasset/22/Barbarian_FuriousCharge_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-ignore-pain.png http://d3db.com/static/gameasset/22/Barbarian_IgnorePain_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-battle-rage.png http://d3db.com/static/gameasset/22/Barbarian_BattleRage_Normal.png
wget -O barbarian-bloodthirst.png http://d3db.com/static/gameasset/22/Traits_Common_Cruelty_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-call-of-the-ancients.png http://d3db.com/static/gameasset/22/Barbarian_CallOfTheAncients_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-overpower.png http://d3db.com/static/gameasset/22/Barbarian_Overpower_Normal.png
wget -O barbarian-animosity.png http://d3db.com/static/gameasset/22/Traits_Barbarian_BadTemper_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-war-cry.png http://d3db.com/static/gameasset/22/Barbarian_WarCry_Normal.png
wget -O barbarian-superstition.png http://d3db.com/static/gameasset/22/Traits_Barbarian_Superstitious_Normal.png
wget -O barbarian-tough-as-nails.png http://d3db.com/static/gameasset/22/Traits_Barbarian_IronSkin_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-wrath-of-the-berserker.png http://d3db.com/static/gameasset/22/Barbarian_WrathOfTheBerserker_Normal.png
wget -O barbarian-no-escape.png http://d3db.com/static/gameasset/22/Traits_Barbarian_frenziedAttacks_Normal.png
wget -O barbarian-relentless.png http://d3db.com/static/gameasset/22/Traits_Barbarian_InsaneCourage_Normal.png
wget -O barbarian-brawler.png http://d3db.com/static/gameasset/22/Traits_Monk_StrengthInAdversity_Normal.png
wget -O barbarian-juggernaut.png http://d3db.com/static/gameasset/22/Traits_Barbarian_ShieldOfIron_Normal.png
wget -O barbarian-unforgiving.png http://d3db.com/static/gameasset/22/Traits_Common_Aggression_Normal.png
wget -O barbarian-boon-of-bul-kathos.png http://d3db.com/static/gameasset/22/Traits_Barbarian_WarPaint_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-hungering-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_HungeringArrow_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-impale.png http://d3db.com/static/gameasset/22/DemonHunter_Ballista_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-entangling-shot.png http://d3db.com/static/gameasset/22/DemonHunter_Entangle_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-caltrops.png http://d3db.com/static/gameasset/22/DemonHunter_Caltrops_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-rapid-fire.png http://d3db.com/static/gameasset/22/DemonHunter_RapidFire_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-smoke-screen.png http://d3db.com/static/gameasset/22/DemonHunter_SmokeScreen_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-vault.png http://d3db.com/static/gameasset/22/DemonHunter_Vault_Normal.png
wget -O demon-hunter-thrill-of-the-hunt.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Opportunity_Normal.png
wget -O demon-hunter-tactical-advantage.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_TacticalAdvantage_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-bola-shot.png http://d3db.com/static/gameasset/22/DemonHunter_BolaShot_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-chakram.png http://d3db.com/static/gameasset/22/DemonHunter_Chakram_Normal.png
wget -O demon-hunter-vengeance.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Vengeance_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-preparation.png http://d3db.com/static/gameasset/22/DemonHunter_Preparation_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-evasive-fire.png http://d3db.com/static/gameasset/22/DemonHunter_EvasiveFire_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-grenades.png http://d3db.com/static/gameasset/22/DemonHunter_Grenades_Normal.png
wget -O demon-hunter-steady-aim.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Marksman_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-shadow-power.png http://d3db.com/static/gameasset/22/DemonHunter_ShadowPower_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-fan-of-knives.png http://d3db.com/static/gameasset/22/DemonHunter_FanOfKnives_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-spike-trap.png http://d3db.com/static/gameasset/22/DemonHunter_SpikeTrap_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-companion.png http://d3db.com/static/gameasset/22/DemonHunter_Companion_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-strafe.png http://d3db.com/static/gameasset/22/DemonHunter_Strafe_Normal.png
wget -O demon-hunter-cull-the-weak.png http://d3db.com/static/gameasset/22/Traits_Common_Intimidation_Normal.png
wget -O demon-hunter-night-stalker.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_CloakOfShadows_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-elemental-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ElementalArrow_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-marked-for-death.png http://d3db.com/static/gameasset/22/DemonHunter_MarkedForDeath_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-multishot-77649.png http://d3db.com/static/gameasset/22/DemonHunter_Multishot_Normal.png
wget -O demon-hunter-brooding.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_FocusedDiscipline_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-sentry.png http://d3db.com/static/gameasset/22/DemonHunter_Sentry_Normal.png
wget -O demon-hunter-hot-pursuit.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_HotPursuit_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-cluster-arrow.png http://d3db.com/static/gameasset/22/DemonHunter_ClusterArrow_Normal.png
wget -O demon-hunter-archery.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Archery_Normal.png
wget -O demon-hunter-numbing-traps.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_NumbingTraps_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-rain-of-vengeance.png http://d3db.com/static/gameasset/22/DemonHunter_RainOfArrows_Normal.png
wget -O demon-hunter-perfectionist.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_YearsOfTraining_Normal.png
wget -O demon-hunter-custom-engineering.png http://d3db.com/static/gameasset/22/Traits_Common_SuperiorSkill_Normal.png
wget -O demon-hunter-grenadier.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_KillingSpree_Normal.png
wget -O demon-hunter-sharpshooter.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Sharpshooter_Normal.png
wget -O demon-hunter-ballistics.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_Ballistics_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-fists-of-thunder.png http://d3db.com/static/gameasset/22/Monk_FistsOfThunder_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-lashing-tail-kick.png http://d3db.com/static/gameasset/22/Monk_LashingTailKick_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-deadly-reach.png http://d3db.com/static/gameasset/22/Monk_DeadlyReach_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-blinding-flash.png http://d3db.com/static/gameasset/22/Monk_BlindingFlash_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-tempest-rush.png http://d3db.com/static/gameasset/22/Monk_Hobble_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-breath-of-heaven.png http://d3db.com/static/gameasset/22/Monk_BreathOfHeaven_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-dashing-strike.png http://d3db.com/static/gameasset/22/Monk_DashingStrike_Normal.png
wget -O monk-resolve.png http://d3db.com/static/gameasset/22/Traits_Common_UnbreakableWill_Normal.png
wget -O monk-fleet-footed.png http://d3db.com/static/gameasset/22/Traits_Monk_Fleet_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-crippling-wave.png http://d3db.com/static/gameasset/22/Monk_CripplingWave_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-wave-of-light.png http://d3db.com/static/gameasset/22/Monk_WaveOfLight_Normal.png
wget -O monk-exalted-soul.png http://d3db.com/static/gameasset/22/Traits_Monk_ExaltedSoul_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-exploding-palm.png http://d3db.com/static/gameasset/22/Monk_ExplodingPalm_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-cyclone-strike.png http://d3db.com/static/gameasset/22/Monk_CycloneStrike_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-way-of-the-hundred-fists.png http://d3db.com/static/gameasset/22/Monk_WayOfTheHundredFists_Normal.png
wget -O monk-transcendence.png http://d3db.com/static/gameasset/22/Traits_Monk_StrengthOfSpirit_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-serenity.png http://d3db.com/static/gameasset/22/Monk_Serenity_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-seven-sided-strike.png http://d3db.com/static/gameasset/22/Monk_SevenSidedStrike_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-mantra-of-evasion.png http://d3db.com/static/gameasset/22/Monk_ResistAura_Normal.png
wget -O monk-chant-of-resonance.png http://d3db.com/static/gameasset/22/Traits_Monk_Resonance_Normal.png
wget -O monk-seize-the-initiative.png http://d3db.com/static/gameasset/22/Traits_Monk_Untouchable_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-sweeping-wind.png http://d3db.com/static/gameasset/22/Monk_SweepingWind_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-mantra-of-retribution.png http://d3db.com/static/gameasset/22/Monk_RetributionAura_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-inner-sanctuary.png http://d3db.com/static/gameasset/22/Monk_InnerSanctuary_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-mystic-ally.png http://d3db.com/static/gameasset/22/Monk_MysticAlly_Normal.png
wget -O monk-the-guardians-path.png http://d3db.com/static/gameasset/22/Traits_Monk_FrenziedAttacks_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-mantra-of-healing.png http://d3db.com/static/gameasset/22/Monk_HolyAura_Normal.png
wget -O monk-sixth-sense.png http://d3db.com/static/gameasset/22/Traits_Monk_SixthSense_Normal.png
wget -O monk-pacifism.png http://d3db.com/static/gameasset/22/Traits_Monk_CounterAttack_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-mantra-of-conviction.png http://d3db.com/static/gameasset/22/Monk_DominateAura_Normal.png
wget -O monk-beacon-of-ytar.png http://d3db.com/static/gameasset/22/Traits_Monk_Harmony_Normal.png
wget -O monk-guiding-light.png http://d3db.com/static/gameasset/22/Traits_Monk_SelflessHealer_Normal.png
wget -O monk-one-with-everything.png http://d3db.com/static/gameasset/22/Traits_Monk_FlawlessTechnique_Normal.png
wget -O monk-combination-strike.png http://d3db.com/static/gameasset/22/Traits_Monk_CombinationStrikes_Normal.png
wget -O monk-near-death-experience.png http://d3db.com/static/gameasset/22/Traits_Monk_NearDeathExperience_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-poison-dart.png http://d3db.com/static/gameasset/22/Witchdoctor_PoisonDart_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-grasp-of-the-dead.png http://d3db.com/static/gameasset/22/Witchdoctor_GraspOfTheDead_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-corpse-spiders.png http://d3db.com/static/gameasset/22/Witchdoctor_CorpseSpiders_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-summon-zombie-dogs.png http://d3db.com/static/gameasset/22/Witchdoctor_SummonZombieDog_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-firebats.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBats_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-horrify.png http://d3db.com/static/gameasset/22/Witchdoctor_Horrify_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-soul-harvest.png http://d3db.com/static/gameasset/22/Witchdoctor_SoulHarvest_Normal.png
wget -O witch-doctor-jungle-fortitude.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_JungleFortitude_Normal.png
wget -O witch-doctor-circle-of-life.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_ZombieDogSpawner_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-plague-of-toads.png http://d3db.com/static/gameasset/22/Witchdoctor_PlagueOfToads_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-haunt.png http://d3db.com/static/gameasset/22/Witchdoctor_Haunt_Normal.png
wget -O witch-doctor-spiritual-attunement.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_SpiritualAttunement_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-sacrifice.png http://d3db.com/static/gameasset/22/Witchdoctor_Sacrifice_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-zombie-charger.png http://d3db.com/static/gameasset/22/Witchdoctor_ZombieCharger_Normal.png
wget -O witch-doctor-gruesome-feast.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_BloodRites_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-walk.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritWalk_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-spirit-barrage.png http://d3db.com/static/gameasset/22/Witchdoctor_SpiritBarrage_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-gargantuan.png http://d3db.com/static/gameasset/22/Witchdoctor_Gargantuan_Normal.png
wget -O witch-doctor-blood-ritual.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_RitualOfBlood_Normal.png
wget -O witch-doctor-bad-medicine.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_BadMedicine_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-locust-swarm.png http://d3db.com/static/gameasset/22/Witchdoctor_LocustSwarm_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-firebomb.png http://d3db.com/static/gameasset/22/Witchdoctor_FireBomb_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-hex.png http://d3db.com/static/gameasset/22/Witchdoctor_Hex_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-acid-cloud.png http://d3db.com/static/gameasset/22/Witchdoctor_AcidCloud_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-mass-confusion.png http://d3db.com/static/gameasset/22/Witchdoctor_MassConfusion_Normal.png
wget -O witch-doctor-zombie-handler.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_ZombieMaster_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-big-bad-voodoo.png http://d3db.com/static/gameasset/22/Witchdoctor_BigBadVoodoo_Normal.png
wget -O witch-doctor-pierce-the-veil.png http://d3db.com/static/gameasset/22/Traits_DemonHunter_CloakOfShadows_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-wall-of-zombies.png http://d3db.com/static/gameasset/22/Witchdoctor_WallOfZombies_Normal.png
wget -O witch-doctor-spirit-vessel.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_SpiritVessel_Normal.png
wget -O witch-doctor-fetish-sycophants.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_FetishLeader_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-fetish-army.png http://d3db.com/static/gameasset/22/Witchdoctor_FetishArmy_Normal.png
wget -O witch-doctor-rush-of-essence.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_Meditation_Normal.png
wget -O witch-doctor-vision-quest.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_ManaRegeneration_Normal.png
wget -O witch-doctor-fierce-loyalty.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_CareOfTheMaster_Normal.png
wget -O witch-doctor-grave-injustice.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_GraveInjustice_Normal.png
wget -O witch-doctor-tribal-rites.png http://d3db.com/static/gameasset/22/Traits_Witchdoctor_Rituals_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-magic-missile.png http://d3db.com/static/gameasset/22/Wizard_MagicMissile_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-ray-of-frost.png http://d3db.com/static/gameasset/22/Wizard_RayOfFrost_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-shock-pulse.png http://d3db.com/static/gameasset/22/Wizard_ChargedBolt_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-frost-nova.png http://d3db.com/static/gameasset/22/Wizard_FrostNova_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-arcane-orb.png http://d3db.com/static/gameasset/22/Wizard_ArcaneOrb_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-diamond-skin.png http://d3db.com/static/gameasset/22/Wizard_DiamondSkin_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-wave-of-force.png http://d3db.com/static/gameasset/22/Wizard_WaveOfForce_Normal.png
wget -O wizard-power-hungry.png http://d3db.com/static/gameasset/22/Traits_Wizard_EnergyReserves_Normal.png
wget -O wizard-blur.png http://d3db.com/static/gameasset/22/Traits_Wizard_Blur_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-spectral-blade.png http://d3db.com/static/gameasset/22/Wizard_SpectralBlade_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-arcane-torrent.png http://d3db.com/static/gameasset/22/Wizard_ArcaneTorrent_Normal.png
wget -O wizard-evocation.png http://d3db.com/static/gameasset/22/Traits_Wizard_TemporalShift_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-energy-twister.png http://d3db.com/static/gameasset/22/Wizard_Tornado_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-ice-armor.png http://d3db.com/static/gameasset/22/Wizard_IceArmor_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-electrocute.png http://d3db.com/static/gameasset/22/Wizard_Electrocute_Normal.png
wget -O wizard-glass-cannon.png http://d3db.com/static/gameasset/22/Traits_Wizard_GlassCannon_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-slow-time.png http://d3db.com/static/gameasset/22/Wizard_SlowTime_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-storm-armor.png http://d3db.com/static/gameasset/22/Wizard_StormArmor_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-explosive-blast.png http://d3db.com/static/gameasset/22/Wizard_ExplosiveBlast_Normal.png
wget -O wizard-prodigy.png http://d3db.com/static/gameasset/22/Traits_Wizard_KnowledgeIsPower_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-magic-weapon.png http://d3db.com/static/gameasset/22/Wizard_MagicWeapon_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-hydra.png http://d3db.com/static/gameasset/22/Wizard_Hydra_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-disintegrate.png http://d3db.com/static/gameasset/22/Wizard_Disintegrate_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-familiar.png http://d3db.com/static/gameasset/22/Wizard_Familiar_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-teleport.png http://d3db.com/static/gameasset/22/Wizard_Teleport_Normal.png
wget -O wizard-astral-presence.png http://d3db.com/static/gameasset/22/Traits_Wizard_AstralPresence_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-mirror-image.png http://d3db.com/static/gameasset/22/Wizard_MirrorImage_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-meteor.png http://d3db.com/static/gameasset/22/Wizard_Meteor_Normal.png
wget -O wizard-illusionist.png http://d3db.com/static/gameasset/22/Traits_Wizard_Telekinesis_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-blizzard.png http://d3db.com/static/gameasset/22/Wizard_Blizzard_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-energy-armor.png http://d3db.com/static/gameasset/22/Wizard_EnergyArmor_Normal.png
wget -O wizard-cold-blooded.png http://d3db.com/static/gameasset/22/Traits_Wizard_BlackIce_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-archon.png http://d3db.com/static/gameasset/22/Wizard_Archon_Normal.png
wget -O wizard-conflagration.png http://d3db.com/static/gameasset/22/Traits_Wizard_Conflagration_Normal.png
wget -O wizard-paralysis.png http://d3db.com/static/gameasset/22/Traits_Wizard_Paralysis_Normal.png
wget -O wizard-galvanizing-ward.png http://d3db.com/static/gameasset/22/Traits_Wizard_ExpertDefense_Normal.png
wget -O wizard-temporal-flux.png http://d3db.com/static/gameasset/22/Traits_Wizard_TemporalFlux_Normal.png
wget -O wizard-critical-mass.png http://d3db.com/static/gameasset/22/Traits_Wizard_CriticalMass_Normal.png
wget -O wizard-arcane-dynamo.png http://d3db.com/static/gameasset/22/Traits_Wizard_EmpoweredArmor_Normal.png
wget -O wizard-unstable-anomaly.png http://d3db.com/static/gameasset/22/Traits_Wizard_UnstableEnergy_Normal.png
wget -O enchantress-charm.png http://d3db.com/static/gameasset/22/Enchantress_Charm_Normal.png
wget -O enchantress-forceful-push.png http://d3db.com/static/gameasset/22/Enchantress_ForcefulPush_Normal.png
wget -O enchantress-reflect-missiles.png http://d3db.com/static/gameasset/22/Enchantress_ReflectMissiles_Normal.png
wget -O enchantress-powered-armor.png http://d3db.com/static/gameasset/22/Enchantress_PoweredArmor_Normal.png
wget -O enchantress-disorient.png http://d3db.com/static/gameasset/22/Enchantress_Disorient_Normal.png
wget -O enchantress-erosion.png http://d3db.com/static/gameasset/22/Enchantress_AmplifyDamage_Normal.png
wget -O enchantress-focused-mind.png http://d3db.com/static/gameasset/22/Enchantress_FocusedMind_Normal.png
wget -O enchantress-mass-control.png http://d3db.com/static/gameasset/22/Enchantress_EnergyBomb_Normal.png
wget -O templar-heal.png http://d3db.com/static/gameasset/22/Templar_Righteous_Heal_Normal.png
wget -O templar-intervene.png http://d3db.com/static/gameasset/22/Templar_Defender_Intervene_Normal.png
wget -O templar-loyalty.png http://d3db.com/static/gameasset/22/Templar_Righteous_Loyalty_Normal.png
wget -O templar-intimidate.png http://d3db.com/static/gameasset/22/Templar_Focus_Intimidate_Normal.png
wget -O templar-charge.png http://d3db.com/static/gameasset/22/Templar_Focus_ShieldCharge_Normal.png
wget -O templar-onslaught.png http://d3db.com/static/gameasset/22/Templar_Righteous_Onslaught_Normal.png
wget -O templar-inspire.png http://d3db.com/static/gameasset/22/Templar_Focus_Inspire_Normal.png
wget -O templar-guardian.png http://d3db.com/static/gameasset/22/Templar_Defender_Empathy_Normal.png
wget -O scoundrel-crippling-shot.png http://d3db.com/static/gameasset/22/Scoundrel_CripplingShot_Normal.png
wget -O scoundrel-poison-bolts.png http://d3db.com/static/gameasset/22/Scoundrel_PoisonArrows_Normal.png
wget -O scoundrel-dirty-fighting.png http://d3db.com/static/gameasset/22/Scoundrel_DirtyFighting_Normal.png
wget -O scoundrel-vanish.png http://d3db.com/static/gameasset/22/Scoundrel_Vanish_Normal.png
wget -O scoundrel-powered-shot.png http://d3db.com/static/gameasset/22/Scoundrel_RapidFire_Normal.png
wget -O scoundrel-multishot.png http://d3db.com/static/gameasset/22/Scoundrel_MultiShot_Normal.png
wget -O scoundrel-hysteria.png http://d3db.com/static/gameasset/22/Scoundrel_PowerShot_Normal.png
wget -O scoundrel-anatomy.png http://d3db.com/static/gameasset/22/Scoundrel_Anatomy_Normal.png
