<table id="table" style="font-size:12px;">
  <thead>
    <tr>
      <th style="width:8px; padding:0px;">
        &nbsp;
      </th>
      <th colspan="14">
        Description with max possible value
      </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td id="C001L" rowspan="5">
        &nbsp;
      </td>
      <td id="C001R">
        BASE ATTRIBUTES
      </td>
      <td title="1-Hand" class="C001R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td title="2-Hand" class="C001R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td title="Bracers" class="C001R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td title="Boots" class="C001R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td title="Ring" class="C001R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td title="Gloves" class="C001R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td title="Helm" class="C001R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td title="Pants" class="C001R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td title="Amulet" class="C001R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td title="Off-Hand" class="C001R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td title="Shoulders" class="C001R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td title="Chest" class="C001R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td title="Belt" class="C001R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(9-595)</span> Strength
      </td>
      <td>
        350
      </td>
      <td>
        595
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        178
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        302
      </td>
      <td>
        350
      </td>
      <td>
        300
      </td>
      <td>
        200
      </td>
      <td>
        300
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(9-595)</span> Dexterity
      </td>
      <td>
        350
      </td>
      <td>
        595
      </td>
      <td>
        200
      </td>
      <td>
        300
      </td>
      <td>
        178
      </td>
      <td>
        300
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        302
      </td>
      <td>
        350
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(9-595)</span> Intelligence
      </td>
      <td>
        350
      </td>
      <td>
        595
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        178
      </td>
      <td>
        300
      </td>
      <td>
        300
      </td>
      <td>
        200
      </td>
      <td>
        302
      </td>
      <td>
        350
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(9-595)</span> Vitality
      </td>
      <td>
        350
      </td>
      <td>
        595
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        178
      </td>
      <td>
        200
      </td>
      <td>
        200
      </td>
      <td>
        300
      </td>
      <td>
        302
      </td>
      <td>
        350
      </td>
      <td>
        200
      </td>
      <td>
        300
      </td>
      <td>
        200
      </td>
    </tr>
    <tr>
      <td id="C010L" rowspan="7">
        &nbsp;
      </td>
      <td id="C010R">
        LIFE
      </td>
      <td title="1-Hand" class="C010R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td title="2-Hand" class="C010R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td title="Bracers" class="C010R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td title="Boots" class="C010R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td title="Ring" class="C010R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td title="Gloves" class="C010R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td title="Helm" class="C010R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td title="Pants" class="C010R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td title="Amulet" class="C010R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td title="Off-Hand" class="C010R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td title="Shoulders" class="C010R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td title="Chest" class="C010R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td title="Belt" class="C010R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(3-16)</span>% Life
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        9
      </td>
      <td></td>
      <td>
        12
      </td>
      <td></td>
      <td>
        14
      </td>
      <td>
        16
      </td>
      <td>
        12
      </td>
      <td>
        12
      </td>
      <td>
        12
      </td>
    </tr>
    <tr>
      <td class="magic">
        Each Hit Adds <span class="val">+(2-1,918)</span> Life
      </td>
      <td>
        959
      </td>
      <td>
        1,918
      </td>
      <td></td>
      <td></td>
      <td>
        328
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        657
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.00-6.00)</span>% of Damage Dealt Is Converted to Life
      </td>
      <td>
        3.00
      </td>
      <td>
        6.00
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        3.00
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(2-5,756)</span> Life after Each Kill
      </td>
      <td>
        2,878
      </td>
      <td>
        5,756
      </td>
      <td></td>
      <td></td>
      <td>
        985
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        1,971
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Regenerates <span class="val">(1-599)</span> Life per Second
      </td>
      <td></td>
      <td></td>
      <td>
        342
      </td>
      <td>
        342
      </td>
      <td>
        234
      </td>
      <td>
        342
      </td>
      <td>
        342
      </td>
      <td>
        342
      </td>
      <td>
        410
      </td>
      <td>
        342
      </td>
      <td>
        342
      </td>
      <td>
        599
      </td>
      <td>
        342
      </td>
    </tr>
    <tr>
      <td class="magic">
        Increases Gold and Health Pickup by <span class="val">(2-7)</span> Yards.
      </td>
      <td></td>
      <td></td>
      <td>
        7
      </td>
      <td>
        7
      </td>
      <td></td>
      <td>
        7
      </td>
      <td>
        7
      </td>
      <td>
        7
      </td>
      <td></td>
      <td></td>
      <td>
        7
      </td>
      <td>
        7
      </td>
      <td>
        7
      </td>
    </tr>
    <tr>
      <td id="C011L" rowspan="8">
        &nbsp;
      </td>
      <td id="C011R">
        ADVENTURE
      </td>
      <td title="1-Hand" class="C011R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td title="2-Hand" class="C011R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td title="Bracers" class="C011R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td title="Boots" class="C011R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td title="Ring" class="C011R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td title="Gloves" class="C011R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td title="Helm" class="C011R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td title="Pants" class="C011R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td title="Amulet" class="C011R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td title="Off-Hand" class="C011R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td title="Shoulders" class="C011R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td title="Chest" class="C011R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td title="Belt" class="C011R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        Sockets (<span class="val">(1-3)</span>)
      </td>
      <td>
        1
      </td>
      <td>
        1
      </td>
      <td></td>
      <td></td>
      <td>
        1
      </td>
      <td></td>
      <td>
        1
      </td>
      <td>
        2
      </td>
      <td>
        1
      </td>
      <td>
        1
      </td>
      <td></td>
      <td>
        3
      </td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(2-40)</span>% Better Chance of Finding Magical Items
      </td>
      <td></td>
      <td></td>
      <td>
        20
      </td>
      <td>
        20
      </td>
      <td>
        18
      </td>
      <td>
        20
      </td>
      <td>
        20
      </td>
      <td>
        20
      </td>
      <td>
        40
      </td>
      <td>
        20
      </td>
      <td>
        20
      </td>
      <td>
        20
      </td>
      <td>
        20
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(5-40)</span>% Extra Gold from Monsters
      </td>
      <td></td>
      <td></td>
      <td>
        25
      </td>
      <td>
        25
      </td>
      <td>
        20
      </td>
      <td>
        25
      </td>
      <td>
        25
      </td>
      <td>
        25
      </td>
      <td>
        40
      </td>
      <td>
        25
      </td>
      <td>
        25
      </td>
      <td>
        25
      </td>
      <td>
        25
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(6-12)</span>% Movement Speed
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        12
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Monster kills grant <span class="val">+(1-24)</span> experience.
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
      <td>
        24
      </td>
    </tr>
    <tr>
      <td class="magic">
        Level Requirement Reduced by <span class="val">(2-18)</span>
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td></td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td></td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
      <td>
        18
      </td>
    </tr>
    <tr>
      <td class="magic">
        Ignores Durability Loss
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td id="C110L" rowspan="14">
        &nbsp;
      </td>
      <td id="C110R">
        DEFENSE
      </td>
      <td title="1-Hand" class="C110R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td title="2-Hand" class="C110R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td title="Bracers" class="C110R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td title="Boots" class="C110R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td title="Ring" class="C110R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td title="Gloves" class="C110R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td title="Helm" class="C110R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td title="Pants" class="C110R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td title="Amulet" class="C110R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td title="Off-Hand" class="C110R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td title="Shoulders" class="C110R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td title="Chest" class="C110R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td title="Belt" class="C110R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(85-397)</span> Armor
      </td>
      <td></td>
      <td></td>
      <td>
        265
      </td>
      <td>
        265
      </td>
      <td>
        240
      </td>
      <td>
        265
      </td>
      <td>
        397
      </td>
      <td>
        397
      </td>
      <td>
        360
      </td>
      <td>
        397
      </td>
      <td>
        265
      </td>
      <td>
        397
      </td>
      <td>
        265
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-80)</span> Resistance to All Elements
      </td>
      <td></td>
      <td></td>
      <td>
        80
      </td>
      <td>
        80
      </td>
      <td>
        70
      </td>
      <td>
        80
      </td>
      <td>
        80
      </td>
      <td>
        80
      </td>
      <td>
        70
      </td>
      <td>
        80
      </td>
      <td>
        80
      </td>
      <td>
        80
      </td>
      <td>
        80
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Physical Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Arcane Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Cold Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Fire Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Lightning Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(11-60)</span> Poison Resistance
      </td>
      <td></td>
      <td></td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        50
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
      <td>
        60
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(1-9)</span>% Chance to Block
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        9
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Reduces damage from elites by <span class="val">(2-7)</span>%.
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        7
      </td>
      <td></td>
      <td>
        7
      </td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Reduces damage from melee attacks by <span class="val">(2-6)</span>%.
      </td>
      <td></td>
      <td></td>
      <td>
        6
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        4
      </td>
      <td>
        6
      </td>
      <td></td>
      <td>
        6
      </td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Reduces damage from ranged attacks by <span class="val">(2-6)</span>%.
      </td>
      <td></td>
      <td></td>
      <td>
        6
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        4
      </td>
      <td>
        6
      </td>
      <td></td>
      <td>
        6
      </td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Reduces the duration of control impairing effects by <span class="val">(5-14)</span>%.
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        14
      </td>
      <td></td>
      <td>
        14
      </td>
      <td></td>
      <td>
        14
      </td>
      <td>
        14
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td id="C100L" rowspan="17">
        &nbsp;
      </td>
      <td id="C100R">
        OFFENSE
      </td>
      <td title="1-Hand" class="C100R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td title="2-Hand" class="C100R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td title="Bracers" class="C100R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td title="Boots" class="C100R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td title="Ring" class="C100R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td title="Gloves" class="C100R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td title="Helm" class="C100R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td title="Pants" class="C100R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td title="Amulet" class="C100R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td title="Off-Hand" class="C100R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td title="Shoulders" class="C100R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td title="Chest" class="C100R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td title="Belt" class="C100R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(10-478)</span> Minimum Damage
      </td>
      <td>
        352
      </td>
      <td>
        478
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(10-611)</span> Maximum Damage
      </td>
      <td>
        447
      </td>
      <td>
        611
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-281)</span>-<span class="val">(2-642)</span> Cold Damage
      </td>
      <td>
        459
      </td>
      <td>
        642
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-442)</span>-<span class="val">(2-1,017)</span> Poison Damage
      </td>
      <td>
        727
      </td>
      <td>
        1,017
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-442)</span>-<span class="val">(2-1,017)</span> Holy Damage
      </td>
      <td>
        727
      </td>
      <td>
        1,017
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-442)</span>-<span class="val">(2-1,017)</span> Arcane Damage
      </td>
      <td>
        727
      </td>
      <td>
        1,017
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-442)</span>-<span class="val">(2-1,017)</span> Lightning Damage
      </td>
      <td>
        727
      </td>
      <td>
        1,017
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        +<span class="val">(1-442)</span>-<span class="val">(2-1,017)</span> Fire Damage
      </td>
      <td>
        727
      </td>
      <td>
        1,017
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(10-50)</span>% Damage
      </td>
      <td>
        50
      </td>
      <td>
        50
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Increases Attack Speed by <span class="val">(2-11)</span>%
      </td>
      <td>
        11
      </td>
      <td>
        11
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Critical Hit Damage Increased by <span class="val">(10-200)</span>%
      </td>
      <td>
        100
      </td>
      <td>
        200
      </td>
      <td></td>
      <td></td>
      <td>
        34
      </td>
      <td>
        50
      </td>
      <td></td>
      <td></td>
      <td>
        65
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Critical Hit Chance Increased by <span class="val">(1.0-10.0)</span>%
      </td>
      <td></td>
      <td></td>
      <td>
        6.0
      </td>
      <td></td>
      <td>
        4.5
      </td>
      <td>
        10.0
      </td>
      <td>
        6.0
      </td>
      <td></td>
      <td>
        8.5
      </td>
      <td>
        10.0
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(2-50)</span> Minimum Damage
      </td>
      <td></td>
      <td>
        50
      </td>
      <td></td>
      <td></td>
      <td>
        36
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        36
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">+(11-86)</span> Maximum Damage
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        86
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        86
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Attack Speed Increased by <span class="val">(2-9)</span>%
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        9
      </td>
      <td>
        9
      </td>
      <td></td>
      <td></td>
      <td>
        9
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        Increases Damage Against Elites by <span class="val">(3-8)</span>%
      </td>
      <td>
        6
      </td>
      <td>
        8
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td id="C101L" rowspan="17">
        &nbsp;
      </td>
      <td id="C101R">
        PROCS
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i0"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i1"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i5"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i9"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i11"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i6"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i2"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i8"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i10"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i12"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i3"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i4"></div>
        </div>
      </td>
      <td class="C101R">
        <div class="pC">
          <div class="p0 i7"></div>
        </div>
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Knockback on Hit
      </td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Immobilize on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Stun on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Fear on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Slow on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Blind on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Chill on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Freeze on Hit
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        5.1
      </td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Freeze on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Slow on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Immobilize on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Chill on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Knockback on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Stun on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Blind on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="magic">
        <span class="val">(1.0-5.1)</span>% Chance to Fear on Hit
      </td>
      <td>
        2.6
      </td>
      <td>
        5.1
      </td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td>
        2.6
      </td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<script type="text/javascript" charset="utf-8">
  $(function() {
    var table = $("#table tbody"),
        data = {},
        keys = [
          '1h',
          '2h',
          'bracers',
          'boots',
          'ring',
          'gloves',
          'helm',
          'pants',
          'amulet',
          'shield',
          'shoulders',
          'chest',
          'belt'
        ];
    table.find("tr").each(function() {
      var row = $(this),
          first = true,
          stat = false,
          count = 0;
      row.find("td").each(function() {
        if(first == true) {
          stat = $(this).text();
          first = false;
          data[stat] = {};
        } else {
          var td = $(this);
          data[stat][keys[count]] = parseFloat($.trim(td.text()));
          count++;          
        }
      });
    });
    console.log(JSON.stringify(data));
  });
</script>