<div class="faq-content ui-widget ui-corner-all ui-widget-content ui-helper-clearfix" style="padding: 0 20px">
	<h2>D3Up.com FAQs</h2>
	<p>Have a question that you think should be answered? Feel free to <a href="mailto:aaron.cox@greymass.com">send me an email</a>!</p>
	<h4 class="table-header">General</h3>
	<ul>
		<li>Coming Soon</li>
	</ul>
	<h4 class="table-header">Builds</h3>
	<ul>
		<li><a href="/faq/gear-based-dps">How is "Gear Based DPS Contributions" calculated?</a></li>
		<li><a href="/faq/gear-based-ehp">How is "Gear Based EHP Contributions" calculated?</a></li>
	</ul>
	<h4 class="table-header">Items</h3>
	<ul>
		<li>Coming Soon</li>
	</ul>
	<h4 class="table-header">My Shop</h3>
	<ul>
		<li><a href="/faq/item-pricer">How does the "Item Pricer" work?</a></li>
	</ul>
</div>