<div class="home inline-flow">
	<div class="recent-builds">
		<table id="recent-builds" class="d3up-table">
			<thead>
				<tr>
					<td colspan="10">
						<div class='filters'>
							By Class: 
							<select name="build-by-class" class="build-selector">
								<option></option>
								<option <?= ($this->buildClass == "barbarian") ? "selected='selected'" : "" ?> value="barbarian">Barbarian</option>
								<option <?= ($this->buildClass == "demon-hunter") ? "selected='selected'" : "" ?> value="demon-hunter">Demon Hunter</option>
								<option <?= ($this->buildClass == "monk") ? "selected='selected'" : "" ?> value="monk">Monk</option>
								<option <?= ($this->buildClass == "witch-doctor") ? "selected='selected'" : "" ?> value="witch-doctor">Witch Doctor</option>
								<option <?= ($this->buildClass == "wizard") ? "selected='selected'" : "" ?> value="wizard">Wizard</option>
							</select>
						</div>
						<h2>Recent Character Builds</h2>
					</td>
				</tr>
			</thead>
			<tbody>
			<? foreach($this->builds as $build): ?>
				<tr>
					<td class="icon"><img src="/images/<?= $build->class ?>.png"/></td>
					<td class="name"><?= $this->mLink($build) ?></td>
					<td><?= $build->description ?></td>
				</tr>
			<? endforeach; ?>
			<tr>
				<td colspan="10" class="more-builds">
					Looking for more Builds? Check out the <a href="/build">Builds Page</a>.
				</td>
			</tr>
			</tbody>
		</table>
		<script type="text/javascript">
			$(".build-selector").bind('change', function() {
				var resultsTable = $(".recent-builds table tbody");
				resultsTable.addClass("ui-state-disabled");
				$.ajax({
					url: '/?build-class=' + $(this).val(),
					type: 'html',
					success: function(data) {
						var results = $("<div/>").append(data);
						resultsTable.replaceWith(results.find(".recent-builds table tbody"));
					}
				});
			});
		</script>
	</div>
	<div class="recent-items">
		<h2>Recently Created Items</h2>
		<ul>
			<? foreach($this->items as $item): ?>
				<li>
					<?= $this->itemLink($item) ?> (<?= ucwords(str_replace("-", " ", $item->type))?>)
				</li>
			<? endforeach; ?>
		</ul>
		<?php echo $this->paginationControl($this->items,
		                                    'Elastic',
		                                    'index/_pages.phtml'); ?>
	</div>
</div>
<div class="info inline-flow">
	<?= $this->render("./post/_updates.phtml")?>
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What is D3Up?</h3>
		<p>D3Up is designed as a tool to help you find information about Items, a place to create varies Character Builds, and compare your items to determine which stats will change.</p>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What can I do here?</h3>
		<ul>
			<li><a href="/item/create">Create Items</a> to share with others or add to your builds.</li>
			<li>Create <a href="/build/create">Character Builds</a>, complete with gear, skills and detailed statistics!</li>
			<li>Compare the items in your build to other items you've created.</li>
		</ul>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
	<h3>Stats</h3>
	<ul>
		<li><?= $this->counts['items']?> items</li>
		<li><?= $this->counts['builds']?> Character Builds</li>
	</ul>
	</div>
</div>