<style type="text/css" media="screen">
	.home {
		margin: 0 10px;
		width: 610px;
	}
	.home h2 {
		margin: 5px 10px;
	}
	.recent-items {
		padding: 2px;
	}
	.info {
		width: 300px;
		margin: 0 10px;
	}
	.info .ui-widget {
		padding: 0 10px;
		margin-bottom: 10px;
	}
	.info .ui-widget h3 {
		color: #70B1D5;
	}
</style>
<div class="home inline-flow">
	<div class="recent-items">
		<h2>Recently Created Items</h2>
		<ul>
			<? foreach($this->items as $item): ?>
				<li>
					<?= $this->itemLink($item) ?> (<?= ucwords(str_replace("-", " ", $item->type))?>)
				</li>
			<? endforeach; ?>
		</ul>
		<?php echo $this->paginationControl($this->items,
		                                    'Elastic',
		                                    'index/_pages.phtml'); ?>
	</div>
	<div class="recent-builds">
		<h2>Recently Created Character Builds</h2>
		<ul>
			<? foreach($this->builds as $build): ?>
				<li>
					<?= $this->mLink($build) ?> (<?= ucwords(str_replace("-", " ", $build->class))?>)
				</li>
			<? endforeach; ?>
		</ul>
		<?php echo $this->paginationControl($this->builds,
		                                    'Elastic',
		                                    'index/_pages.phtml'); ?>
	</div>
</div>
<div class="info inline-flow">
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What is D3Up?</h3>
		<p>D3Up is designed as a tool to help you find information about Items, a place to create varies Character Builds, and compare your items to determine which stats will change.</p>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What can I do here?</h3>
		<ul>
			<li><a href="/item/create">Create Items</a> to share with others or add to your builds.</li>
			<li>Create <a href="/build/create">Character Builds</a>, complete with gear, skills and detailed statistics!</li>
			<li>Compare the items in your build to other items you've created.</li>
		</ul>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
	<h3>Stats</h3>
	<ul>
		<li><?= $this->counts['items']?> items</li>
		<li><?= $this->counts['builds']?> Character Builds</li>
	</ul>
	</div>
</div>