<div class="home inline-flow">
	<div class="recent-builds">
		<h2 class="table-header">Recent Character Builds</h2>
		<table id="recent-builds" class="d3up-table">
			<tbody>
			<? foreach($this->builds as $build): ?>
				<tr class="item-row">
					<td class="icon"><img src="/images/<?= $build->class ?>.png"/></td>
					<td class="name"><?= $this->mLink($build) ?></td>
					<td><?= $build->description ?></td>
				</tr>
			<? endforeach; ?>
			</tbody>
		</table>
	</div>
	<div class="recent-items">
		<h2 class='table-header'>Recently Created Items</h2>
		<table class="d3up-table">
		<tbody>
			<? foreach($this->items as $item): ?>
			<tr class="item-row" id="item-<?= $item->id ?>">
					<td class="name">
						<div class="item-stat">
							<span class="value">
								<?= $this->itemLink($item) ?>
							</span>
						<? if($item->stats): ?>
							<span class="stat">
							<? if($item->stats->armor): ?>
								<?= $item->stats->armor . " Armor"?>
							<? endif; ?>
							<? if($item->stats->dps): ?>
								<?= $item->stats->dps." dps" ." @ ".$item->stats->speed." A/S" ?>
							<? endif; ?>
							</span>
						<? endif; ?>
					</td>
					<?
						if($item->stats) {
							$stats = $item->stats->export();								
						}
						$attrs = $item->attrs->getAttributesArray($item->type);
						$export = $item->cleanExport();
						if(isset($export['socketAttrs'])) {
							$socketAttrs = $export['socketAttrs'];
						}
						// Put whatever we're filtering in first 
						if($this->sortAttrs) {
							foreach($this->sortAttrs as $k => $v) {
								switch($v) {
									case "base_armor":
										$val = $stats['armor'];
										break;
									case "base_dps":
										$val = $stats['dps'];
										break;
									default:
										$val = $attrs[$v];
										break;
								}
								if(isset($socketAttrs[$k])) {
									$val += $socketAttrs[$k];
								}
								unset($attrs[$v]);
								echo "<td class='sorted'>".$this->itemStat(ucwords(str_replace("_", " ", $v)), $val)."</td>";							
							}
						}
						$count = count($this->sortAttrs);
					?>
					<? foreach($attrs as $k => $v): ?>
						<? 
							$count++;
							$val = $v;
							if(isset($socketAttrs[$k])) {
								$val += $socketAttrs[$k];
							}
						?>
						<? if($count > 6) { continue; } ?>
						<td><?= $this->itemStat($k, $val) ?></td>
					<? endforeach ?>
					<? if($count < 6): ?>
						<? for($i = $count; $i < 6; $i++): ?>
							<td>&nbsp;</td>
						<? endfor ?>
					<? endif ?>

				</tr>
			<? endforeach; ?>
		</tbody>
	</table>
	</div>
</div>
<div class="info inline-flow">
	<?= $this->render("./post/_updates.phtml")?>
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What is D3Up?</h3>
		<p>D3Up is designed as a tool to help you find information about Items, a place to create varies Character Builds, and compare your items to determine which stats will change.</p>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
		<h3>What can I do here?</h3>
		<ul>
			<li><a href="/item/create">Create Items</a> to share with others or add to your builds.</li>
			<li>Create <a href="/build/create">Character Builds</a>, complete with gear, skills and detailed statistics!</li>
			<li>Compare the items in your build to other items you've created.</li>
		</ul>
	</div>
	<div class='ui-widget ui-widget-content ui-corner-all'>
	<h3>Stats</h3>
	<ul>
		<li><?= $this->counts['items']?> items</li>
		<li><?= $this->counts['builds']?> Character Builds</li>
	</ul>
	</div>
</div>