<?php if ($this->pageCount > 1): ?>
<?
	$params = "";
	if($this->itemType) {
		$params .= "&type=".$this->itemType;
	}
	if($this->sortAttrs) {
		$params .= "&sort=".implode(",",$this->sortAttrs);
	}
?>
<div style="text-align: right">
	<!-- Previous page link -->
	<?php if ($this->prevoius != 1 && $this->current != 1): ?>
		<a href="?page=1<?= $params ?>">&laquo;</a>
	<?php endif; ?>
	<?php if (isset($this->previous)): ?>
		<a href="?page=<?= $this->previous ?><?= $params ?>">&lsaquo;</a>
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
			<a href="?page=<?= $page ?><?= $params ?>"><?php echo $page; ?></a>
		<?php else: ?>
			<span><?php echo $page; ?></span>
		<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
		<a href="?page=<?= $this->next ?><?= $params ?>">&rsaquo;</a>
	<?php endif; ?>
	<?php if (isset($this->last) && $this->last != $this->next && $this->last != $this->current): ?>
		<a href="?page=<?= $this->last ?><?= $params ?>">&raquo;</a>
	<?php endif; ?>
</div>
<?php endif; ?>