<?php if ($this->pageCount > 1): ?>
<?
	$params = "";
	if($this->itemType) {
		$params .= "&type=".$this->itemType;
	}
	if($this->slotType) {
		$params .= "&slot=".$this->slotType;
	}
	if($this->sortAttrs) {
		$params .= "&sort=".implode(",",$this->sortAttrs);
	}
	if($this->sellMethod) {
		$params .= "&sellMethod=".$this->sellMethod;
	}
	if($this->limit) {
		$params .= "&limit=".$this->limit;
	}
?>
<div id="item-pagination" class='button-bar' style="float: right">
	<!-- Previous page link -->
	<?php if ($this->prevoius != 1 && $this->current != 1): ?>
		<a class='button' href="?page=1<?= $params ?>">&laquo;</a>
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
			<a class='button' href="?page=<?= $page ?><?= $params ?>"><?php echo $page; ?></a>
		<?php else: ?>
			<span class='button'><?php echo $page; ?></span>
		<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->last) && $this->last != $this->next && $this->last != $this->current): ?>
		<a class='button' href="?page=<?= $this->last ?><?= $params ?>">&raquo;</a>
	<?php endif; ?>
</div>
<?php endif; ?>