<div class="create-form ui-widget ui-widget-content ui-corner-all">
	<form method="post">
		<div class="item-preview">
			<h3>Item Preview</h3>
			<div class="d3-item">
				<div class="top"><p class="">Name</p></div>
				<div class="item">
					<p class="item-type">
						<span class="quality">Quality</span>
						<span class="type">Type</span>
					</p>
					<p class="stats stats-primary">
						<span class="big-stat"></span>
						<span class="stat-helper"></span>
					</p>
					<p class="stats stats-extra-percent"></p>
					<p class="stats stats-extra-range"></p>
					<ul class="attrs">
					</ul>
					<ul class="sockets">
					</ul>
				</div>
				<div class="bottom"> 
					<? if($profile = Epic_Auth::getInstance()->getProfile()): ?>
						Created by: <?= $profile->username ?>
					<? endif; ?>
				</div>
			</div>
		</div>
		<div>
			<?= $this->form ?>
		</div>
	</form>
</div>
<script type="text/javascript" src="/js/item.js"></script>
<script type="text/javascript">
<? if($this->record->id): ?>
var post = <?= json_encode($this->record->cleanExport()) ?>;
$("ul.attrs li input").each(function() {
	$(this).val(post['attrs'][$(this).attr("name")]);
});
$("ul.sockets li select").each(function() {
	var idx = $(this).attr("name").replace("socket","");
	$(this).val(post['sockets'][idx]);
	$(this).trigger("change");
	// $(this).parent().find(".select2-container span").html($(this));
});
<? endif ?>
<? if(!empty($_POST)): ?>
var post = <?= json_encode($_POST) ?>;
$("ul.attrs li input").each(function() {
	$(this).val(post[$(this).attr("name")]);
});
$(".create-form input").each(function() {
	$(this).val(post[$(this).attr("name")]);
	$(this).trigger("keyup");
});
<? endif ?>
</script>