<?
	$this->headTitle("Create a Diablo 3 Item"); 
?>
<div class="content-page">
  <div class='form'>
  	<form method="post">
  		<div id="simulate-item" class="d3-item item-preview"></div>
  		<div>
  			<h2>Create an Item</h2>
  			<?= $this->form ?>
  		</div>
  	</form>
  </div>
</div>
<script type="text/javascript">
$(function() {
	// Establish the Builder
	var builder = new d3up.ItemBuilder;
	// Set the Name Field
	builder.setNameInput($("#name"));
	// Set the Quality Selector
	builder.setQualitySelect($("#quality"));
	// Set the Type Selector
	builder.setItemTypeSelect($("#itemType"));
	// Set the Attribute Selector
	builder.setAttributeSelect($("#attributes"));
	// Set the Socket selector
	builder.setSocketSelect($("#sockets"));
	// Set the Item Preview
	builder.setItemPreview($("#simulate-item"));
	// Initialize the Item Builder
	builder.init();
	<? if($this->record->id): ?>
	builder.setItem('create', <?= json_encode($this->record->cleanExport()) ?>);
	<? endif ?>

	$("#quality").chosen({
		placeholder: 'Choose the item\'s quality...',
		allowClear: true
	});
	$("#sockets").chosen({
		placeholder: 'No Sockets...',
		allowClear: true
	});
  $("#attributes").chosen({
   placeholder: 'What attributes does this item have?',
   allowClear: true
  });
	$("#itemType").chosen({
		placeholder: 'Choose the item type...',
		allowClear: true
	});

	<? if(!empty($_POST)): ?>
	$("#sockets, #attributes, #quality, #itemType").trigger('change');
	var post = <?= json_encode($_POST) ?>;
	$(".item-preview input").each(function() {
		$(this).val(post[$(this).attr("name")]);
	});
	$(".item-preview select").each(function() {
		$(this).val(post[$(this).attr("name")]);
	});
	$(".create-form input").each(function() {
		$(this).val(post[$(this).attr("name")]);
		// $(this).trigger("keyup");
	});
	if(post.setBonus) {
		$("#setBonus").val(post.setBonus);
	}
	<? endif ?>
	
});
</script>
