<? $profile = Epic_Auth::getInstance()->getProfile(); ?>
<? if(!$this->disableScripts): ?>
	<?
		$this->headTitle('Item Search'); 
		if($profile) {
			$query = array(
				'_createdBy' => $profile->createReference()
			);
			$builds = Epic_Mongo::db('build')->fetchAll($query);
		}
	?>
	<div class="item-list">
		<div class="filters">
			<? if($profile): ?>
			<select id="buildSelect" data-placeholder="Compare Items against build...">
				<option value=""></option>
				<? foreach($builds as $build): ?>
					<option value="<?= $build->id ?>"><?= $build->name ?></option>
				<? endforeach ?>
			</select>
			<? endif; ?>
			<select data-placeholder="Filter by Slot" id="slotType" name="slotType" style="width: 150px">
		    <option label="" value=""></option>
				<? foreach(D3Up_Mongo_Record_Item::$slotTypeMap as $slot => $type): ?>
					<? 
						switch($slot) {
							case "ring1":
								$name = "ring";
								break;
							case "ring2":
								$name = null;
								break;
							default:
								$name = $slot;
								break;
						}
					?>
					<? if($name): ?>
			    	<option label="<?= ucfirst($name) ?>" value="<?= $slot ?>"><?= ucfirst($name) ?></option>					
					<? endif; ?>
				<? endforeach ?>
			</select>
			<select data-placeholder="Filter by Item Type" id="itemType" name="itemType">
		    <option label="" value=""></option>
		    <option label="Amulet" value="amulet">Amulet</option>
		    <option label="Belt" value="belt">Belt</option>
		    <option label="Boots" value="boots">Boots</option>
		    <option label="Bracers" value="bracers">Bracers</option>
		    <option label="Chest Armor" value="chest">Chest Armor</option>
		    <option label="Cloak" value="cloak">Cloak</option>
		    <option label="Gloves" value="gloves">Gloves</option>
		    <option label="Helm" value="helm">Helm</option>
		    <option label="Pants" value="pants">Pants</option>
		    <option label="Mighty Belt" value="mighty-belt">Mighty Belt</option>
		    <option label="Ring" value="ring">Ring</option>
		    <option label="Shoulders" value="shoulders">Shoulders</option>
		    <option label="Spirit Stone" value="spirit-stone">Spirit Stone</option>
		    <option label="Voodoo Mask" value="voodoo-mask">Voodoo Mask</option>
		    <option label="Wizard Hat" value="wizard-hat">Wizard Hat</option>
		    <option label="Two-Handed Mace" value="2h-mace">Two-Handed Mace</option>
		    <option label="Two-Handed Axe" value="2h-axe">Two-Handed Axe</option>
		    <option label="Bow" value="bow">Bow</option>
		    <option label="Diabo" value="diabo">Diabo</option>
		    <option label="Crossbow" value="crossbow">Crossbow</option>
		    <option label="Two-Handed Mighty Weapon" value="2h-mighty">Two-Handed Mighty Weapon</option>
		    <option label="Polearm" value="polearm">Polearm</option>
		    <option label="Staff" value="staff">Staff</option>
		    <option label="Two-Handed Sword" value="2h-sword">Two-Handed Sword</option>
		    <option label="Axe" value="axe">Axe</option>
		    <option label="Ceremonial Knife" value="ceremonial-knife">Ceremonial Knife</option>
		    <option label="Hand Crossbow" value="hand-crossbow">Hand Crossbow</option>
		    <option label="Dagger" value="dagger">Dagger</option>
		    <option label="Fist Weapon" value="fist-weapon">Fist Weapon</option>
		    <option label="Mace" value="mace">Mace</option>
		    <option label="Mighty Weapon" value="mighty-weapon">Mighty Weapon</option>
		    <option label="Spear" value="spear">Spear</option>
		    <option label="Sword" value="sword">Sword</option>
		    <option label="Wand" value="wand">Wand</option>
		    <option label="Mojo" value="mojo">Mojo</option>
		    <option label="Source" value="source">Source</option>
		    <option label="Quiver" value="quiver">Quiver</option>
		    <option label="Shield" value="shield">Shield</option>
			</select>
		</div>
		<h2 class="table-header">Item Search</h2>
		<table id="recent-items" class="d3up-table">
			<thead>
				<tr>
					<td colspan="100" class="sorting">
						<select data-placeholder="Filter & Sort by Multiple Stats" id="sortAttributes" multiple="multiple">
							<option label="Sockets" value="has_sockets">Sockets</option>
							<option label="DPS" value="base_dps">DPS</option>
							<option label="Armor" value="base_armor">Armor</option>
							<?= $this->render("./item/_itemAttributeOptions.phtml") ?>
						</select>
					</td>
				</tr>
			</thead>
<? endif; ?>
	<? if(!count($this->items)): ?>
		<tbody>
			<tr>
				<td colspan="10">	
					<h3 style="text-align: center; color: #f00">No Items found with your search parameters</h3>
				</td>
			</tr>
		</tbody>
		<? exit; ?>
	<? endif ?>
			<tbody>
				<tr>
					<td colspan="10" class="item-paginator td-paginator">
						<?php echo $this->paginationControl($this->items,
						                                    'Elastic',
						                                    'item/_pages.phtml',
																								array(
																									'itemType' => $this->itemType,
																									'sortAttrs' => $this->sortAttrs,
																									'slotType' => $this->slotType,
																								)); ?>
					</td>
				</tr>
				<? foreach($this->items as $item): ?>
				<tr class="item-row" id="item-<?= $item->id ?>">
						<td class="name">
							<div class="item-stat">
								<span class="value">
									<?= $this->itemLink($item) ?>
								</span>
							<? if($item->stats): ?>
								<span class="stat">
								<? if($item->stats->armor): ?>
									<?= $item->stats->armor . " Armor"?>
								<? endif; ?>
								<? if($item->stats->dps): ?>
									<?= $item->stats->dps." dps" ." @ ".$item->stats->speed." A/S" ?>
								<? endif; ?>
								</span>
							<? endif; ?>
						</td>
						<?
							if($item->stats) {
								$stats = $item->stats->export();								
							}
							$socketAttrs = array();
							$attrs = $item->attrs->getAttributesArray($item->type);
							$export = $item->cleanExport();
							if(isset($export['socketAttrs'])) {
								$socketAttrs = $export['socketAttrs'];
							}
							// Put whatever we're filtering in first 
							if($this->sortAttrs) {
								foreach($this->sortAttrs as $k => $v) {
									switch($v) {
										case "has_sockets":
											$val = count($item->sockets);
											break;
										case "base_armor":
											$val = $stats['armor'];
											break;
										case "base_dps":
											$val = $stats['dps'];
											break;
										default:
											$val = $attrs[$v];
											break;
									}
									if(isset($socketAttrs[$k])) {
										$val += $socketAttrs[$k];
									}
									unset($attrs[$v]);
									echo "<td class='sorted'>".$this->itemStat($v, $val, $item->rating[$v])."</td>";							
								}
							}
							$count = count($this->sortAttrs);
						?>
						<? foreach($attrs as $k => $v): ?>
							<? 
								$count++;
								$val = $v;
								if(isset($socketAttrs[$k])) {
									$val += $socketAttrs[$k];
								}
							?>
							<? if($count > 6) { continue; } ?>
							<td><?= $this->itemStat($k, $val, $item->rating[$k]) ?></td>
						<? endforeach ?>
						<? if($count < 6): ?>
							<? for($i = $count; $i < 6; $i++): ?>
								<td>&nbsp;</td>
							<? endfor ?>
						<? endif ?>
						<? if($profile): ?>
						<td class='controls'>
								<?= $this->mLink($item, array('action' => 'copy', 'text' => 'Copy'))?>
								<a class="compareThis" data-item="<?= $item->id ?>">Compare</a>
						</td>
					<? endif ?>
					</tr>
				<? endforeach; ?>
				<tr>
					<td colspan="10" class="item-paginator td-paginator">
						<?php echo $this->paginationControl($this->items,
						                                    'Elastic',
						                                    'item/_pages.phtml',
																								array(
																									'itemType' => $this->itemType,
																									'sortAttrs' => $this->sortAttrs,
																									'slotType' => $this->slotType,																									
																								)); ?>
					</td>
				</tr>
			</tbody>
<? if(!$this->disableScripts): ?>
		</table>
	</div>
	<? if($profile): ?>
	<div id="my-builds">
		<? foreach($builds as $build): ?>
		<div class="build-parent" id="build-<?= $build->id ?>" data-class="<?= $build->class ?>">
			<div class="build-items">
				<? foreach($build->equipment as $slot => $gear):?>
					<span class="<?= $slot ?>" data-slot="<?= $slot ?>"><?= $this->itemLink($gear) ?></span>
				<? endforeach ?>
			</div>
			<div class="build-passives" data-json='<?= ($build->passives)?json_encode($build->passives->export()):"" ?>'></div>
		</div>
		<? endforeach ?>
	</div>
	<? endif ?>

	<? if($this->itemType): ?>
	<script type="text/javascript">
		$(function() {
			$("#itemType").find("option[value=<?= $this->itemType ?>]").attr("selected", "selected");			
		});
		<? if($this->sortAttrs) {
			foreach($this->sortAttrs as $attr) {
				echo "$('#sortAttributes option[value=".$attr."]').attr('selected','selected');";					
			}
		} ?>
	</script>
	<? endif ?>
	<script type="text/javascript" src="/js/skills.js"></script>
	<script type="text/javascript" src="/js/calc.js"></script>
	<script type="text/javascript" src="/js/browser.js"></script>
<? endif ?>