<div id="pricer" class="inline-flow">
	<ul>
		<li><a href="#build-gear">Search</a></li>
	</ul>
	<div id="pricer-simulate" class="pricer-tab">
		<p>Need Help? Read more on the <a href="/faq/item-pricer">Item Pricer's FAQ</a>.</p>
		<p>What type of item is this?</p>
		<p>
			<select name="itemType" id="itemType" data-placeholder="What type of item is this?">
			    <option value="" label="" selected="selected"></option>
			    <option value="amulet" label="Amulet">Amulet</option>
			    <option value="belt" label="Belt">Belt</option>
			    <option value="boots" label="Boots">Boots</option>
			    <option value="bracers" label="Bracers">Bracers</option>
			    <option value="chest" label="Chest Armor">Chest Armor</option>
			    <option value="cloak" label="Cloak">Cloak</option>
			    <option value="gloves" label="Gloves">Gloves</option>
			    <option value="helm" label="Helm">Helm</option>
			    <option value="pants" label="Pants">Pants</option>
			    <option value="mighty-belt" label="Mighty Belt">Mighty Belt</option>
			    <option value="ring" label="Ring">Ring</option>
			    <option value="shoulders" label="Shoulders">Shoulders</option>
			    <option value="spirit-stone" label="Spirit Stone">Spirit Stone</option>
			    <option value="voodoo-mask" label="Voodoo Mask">Voodoo Mask</option>
			    <option value="wizard-hat" label="Wizard Hat">Wizard Hat</option>
			    <option value="2h-mace" label="Two-Handed Mace">Two-Handed Mace</option>
			    <option value="2h-axe" label="Two-Handed Axe">Two-Handed Axe</option>
			    <option value="bow" label="Bow">Bow</option>
			    <option value="diabo" label="Diabo">Diabo</option>
			    <option value="crossbow" label="Crossbow">Crossbow</option>
			    <option value="2h-mighty" label="Two-Handed Mighty Weapon">Two-Handed Mighty Weapon</option>
			    <option value="polearm" label="Polearm">Polearm</option>
			    <option value="staff" label="Staff">Staff</option>
			    <option value="2h-sword" label="Two-Handed Sword">Two-Handed Sword</option>
			    <option value="axe" label="Axe">Axe</option>
			    <option value="ceremonial-knife" label="Ceremonial Knife">Ceremonial Knife</option>
			    <option value="hand-crossbow" label="Hand Crossbow">Hand Crossbow</option>
			    <option value="dagger" label="Dagger">Dagger</option>
			    <option value="fist-weapon" label="Fist Weapon">Fist Weapon</option>
			    <option value="mace" label="Mace">Mace</option>
			    <option value="mighty-weapon" label="Mighty Weapon">Mighty Weapon</option>
			    <option value="spear" label="Spear">Spear</option>
			    <option value="sword" label="Sword">Sword</option>
			    <option value="wand" label="Wand">Wand</option>
			    <option value="mojo" label="Mojo">Mojo</option>
			    <option value="source" label="Source">Source</option>
			    <option value="quiver" label="Quiver">Quiver</option>
			    <option value="shield" label="Shield">Shield</option>
			</select>
		</p>
		<p>What attributes does this item have?</p>
		<p>
			<select id="simulate-attributes" data-placeholder="Select which attributes are on the item" multiple="multiple" style="width: 510px">
				<?= $this->render("./item/_itemAttributeOptions.phtml") ?>
				<option value="armor" label="+ Armor">+ Armor</option>
			</select>
		</p>
		<div id="simulate-stats" class="d3-item"></div>
	</div>
</div>
<div id="pricer-stats" class="pricer-stats ui-widget ui-widget-content ui-corner-all inline-flow" style="width: 385px">
	<ul>
		<li><a href="#tab-similar">Similar Items</a></li>
	</ul>
	<div id="tab-similar" class="stats-tab">
		<table id="similar-items" class='d3up-table'></table>
	</div>
</div>

<script type="text/javascript">
	$("#pricer").tabs();
	$("#pricer-stats").tabs();
	$("#simulate-attributes, #itemType").chosen();
	var similar = $("#similar-items");
	var builder = new itemBuilder();
	// Set the Type Selector
	builder.setItemTypeSelect($("#itemType"));
	// Set the Attribute Selector
	builder.setAttributeSelect($("#simulate-attributes"));
	// Set the Item Preview
	builder.setItemPreview($("#simulate-stats"));
	// Initialize the Item Builder
	builder.init();
	// Create our compare button
	var button = $("<button>Find Similar Items</button>");
	button.click(function() {
		var item = builder.getItem();
		if(item.type == null) {
			$("<p>You need to select the type of item.</p>").dialog({
				height: 140,
				modal: true,
				title: 'Error'
			});
			return false;
		}
		$.ajax({
			data: item,
			success: function(data) {
				similar.empty();
				var json = JSON.parse(data);
				$.each(json, function(k,v) {
					var item = v.item,
							link = $('<a class="quality-'+item.quality+'" href="/i/'+item.id+'">'+item.name+'</a>').attr("data-json", JSON.stringify(v.item)),
							tr = $("<tr class='item-row'/>");
					link.bindTooltip();
					tr.append($("<td class='name'/>").append(link));
					tr.append($("<td class='sold-"+v.status+"'/>").append('<img src="/images/' + v.method + '.png"> ' + v.price));
					tr.append($("<td/>").append(v.date));
					similar.append(tr);
				});
				if(!json.length) {
					similar.append("<tr><td colspan='3'>No similar items found!</td></tr>");
				}
			}
		});
	});
	builder.addFooter(button);
</script>