<div style="padding: 20px;">
	<p>I've added a more comprehensive tool that lets you search and filter all completed auctions. You can find it in the navigation on the top of the page under 'Items', and it's called '<a href="/item/sales-history">Sales History</a>'. It uses the same search tools as the other item search pages to help you filter down results.</p>
	<p>This page shows the last 50 sales from all users.</p>
</div>
<table id="user-complete" class="d3up-table">
	<thead>
		<tr>
			<th>Date</th>
			<th>Item</th>
			<th>Result</th>
			<th>Where</th>
			<th>Bid</th>
			<th>Buyout</th>
			<th>Sold For</th>
	</thead>
	<tbody>
		<? foreach($this->allcompleted as $sale): ?>
			<tr class="item-row" id="sale-<?= $sale->id ?>">
				<td class="data"><?= $this->timeAgo($sale->soldOn) ?></td>
				<td class='name'><?= $this->itemLink($sale->item) ?></td>
				<td class="data">
					<? if($sale->soldSuccess): ?>
						<span class='pos'>Sold</span> 
					<? else: ?>
						<span class='neg'>Not Sold</span>
					<? endif ?>
				</td>
				<td class='data'>
					<?= $this->methodCleaner($sale->method) ?>
				</td>
				<td class='data'>
					<?= $this->priceDisplay($sale, 'bid') ?>
				</td>
				<td class='data'>
					<?= $this->priceDisplay($sale, 'buyout') ?>
				</td>
				<td class='data'>
					<?= $this->priceDisplay($sale, 'soldFor') ?>
				</td>
			</tr>
		<? endforeach ?>
	</tbody>
</table>