<table id="user-complete" class="d3up-table">
	<thead>
		<tr>
			<th>Item</th>
			<th>Results</th>
			<th>Sales Method</th>
			<th>Sale Info</th>
			<th>Sold For</th>
			<th>Date</th>
	</thead>
	<tbody>
		<? foreach($this->completed as $sale): ?>
			<tr class="item-row" id="sale-<?= $sale->id ?>">
				<td class='name'><?= $this->saleLink($sale) ?></td>
				<td class="data">
					<? if($sale->soldSuccess): ?>
						<span class='pos'>Sold</span> 
					<? else: ?>
						<span class='neg'>Not Sold</span>
					<? endif ?>
				</td>
				<td class='data'>
					<?= $this->methodCleaner($sale->method) ?>
				</td>
				<td class='data'>
					<img src="/images/goldcoin.png"> 
					<? if($sale->method == 'ah'): ?>
						<?= $this->prettyStat($sale->buyout) ?> bin / 
						<?= $this->prettyStat($sale->bid) ?> bid
					<? else: ?>
					<? endif ?>
				</td>
				<td class="data"> 
					<div class='item-stat'>
						<? if($sale->method == 'ah'): ?>
							<span class='value'>
								<img src="/images/goldcoin.png"> <?= $this->prettyStat($sale->soldFor) ?>
							</span>
							<span class="stat">
								<?= $this->prettyStat($sale->soldFor / 0.85) ?> before AH cut
							</span>
						<? else: ?>
						<? endif ?>
					</div>
				</td>
				<td class="data"><?= $this->timeAgo($sale->soldOn) ?></td>
			</tr>
		<? endforeach ?>
	</tbody>
</table>