<table id="user-complete" class="d3up-table">
	<thead>
		<tr>
			<th>Date</th>
			<th>Item</th>
			<th>Result</th>
			<th>Where</th>
			<th>Bid</th>
			<th>Buyout</th>
			<th>Sold For</th>
	</thead>
	<tbody>
		<? foreach($this->completed as $sale): ?>
			<tr class="item-row" id="sale-<?= $sale->id ?>">
				<td class="data"><?= $this->timeAgo($sale->soldOn) ?></td>
				<td class='name'><?= $this->itemLink($sale->item) ?></td>
				<td class="data">
					<? if($sale->soldSuccess): ?>
						<span class='pos'>Sold</span> 
					<? else: ?>
						<span class='neg'>Not Sold</span>
					<? endif ?>
				</td>
				<td class='data'>
					<?= $this->methodCleaner($sale->method) ?>
				</td>
				<td class='data'>
					<?= $this->priceDisplay($sale, 'bid') ?>
				</td>
				<td class='data'>
					<?= $this->priceDisplay($sale, 'buyout') ?>
				</td>
				<td class="data"> 
					<?= $this->priceDisplay($sale, 'soldFor') ?>
				</td>
				<td class="controls"><?= $this->mLink($sale, array('action' => 'edit', 'text' => 'Edit')) ?></td>
			</tr>
		<? endforeach ?>
	</tbody>
</table>