<table id="user-shop" class="d3up-table">
	<thead>
		<tr>
			<th>Item</th>
			<th>Method</th>
			<th>Price</th>
			<th>Ends</th>
	</thead>
	<tbody>
		<? foreach($this->forSale as $sale): ?>
			<tr class="item-row" id="sale-<?= $sale->id ?>">
				<td class='name'><?= $this->itemLink($sale->item) ?></td>
				<td class="data">
					<?= $this->methodCleaner($sale->method) ?>
				</td>
				<td class="data"> 
					<?= $this->priceDisplay($sale) ?>
				</td>
				<td class="data"><?= $this->timeAgo($sale->end) ?></td>
				<td class="controls">
					<? if($sale->method == 'ah' || $sale->method == 'rmah'): ?>
						<button data-id="<?= $sale->id ?>" data-item="<?= $sale->item->id ?>" data-method="<?= $sale->method ?>" style="padding: 0px 10px" class="btn-complete ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">Complete</button>
					<? else: ?>
						<a data-id="<?= $sale->id ?>" data-method="<?= $sale->method ?>" style="padding: 0px 10px" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="/sale/<?= $sale->id ?>/offers">View</a>
					<? endif ?>
					<button data-id="<?= $sale->id ?>" style="padding: 0px 10px" class="btn-cancel ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only">Cancel</button>							
				</td>
			</tr>
		<? endforeach ?>
	</tbody>
</table>