<style type="text/css">
	.d3up-table.kpi td {
		width: 33%;
	}
	.bar {
		border: 1px solid #000;
		height: 15px;
		background: #0d0;
		color: #000;
		font-size: 12px;
		text-align: right;
		line-height: 15px;
		padding: 4px;
		min-width: 20px;
	}
	.bar.bar-neg {
		background: #d00;		
	}
	.kpi {
		font-size: 2em;
		padding: 10px 25px;
		margin-bottom: 30px;
	}
</style>
<?
	$data = array(
		'totals' => array(
			'value' 				=> array('ah' => 0, 'rmah' => 0),
			'sales' 				=> array('ah' => 0, 'rmah' => 0),
			'failed' 				=> array('ah' => 0, 'rmah' => 0),
			'pendingSales' 	=> array('ah' => 0, 'rmah' => 0),
			'pendingBuyout' => array('ah' => 0, 'rmah' => 0),
			'pendingBid' 		=> array('ah' => 0, 'rmah' => 0),
			'expenses' => 0,
		),
		'dates' => array(
			'ah' => array(),
			'rmah' => array(),
		),
	);
	$data['totals']['expenses'] = 0;
 	$data['dates'] = array();
	foreach($this->expenses as $expense) {
		$date = strtotime(date("Y-m-d", $expense->date));
		if(!isset($data['dates']['expenses'][$date])) {
			$data['dates']['expenses'][$date]['sales'] = 0;
			$data['dates']['expenses'][$date]['value'] = 0;
			$data['dates']['expenses'][$date]['failed'] = 0;
			$data['dates']['expenses'][$date]['expenses'] = 0;	
		}
		$data['dates']['expenses'][$date]['expenses'] += $expense->amount;
		$data['totals']['expenses'] += $expense->amount;
	}
	foreach($this->allSales as $sale) {
		$date = strtotime(date("Y-m-d", $sale->soldOn));
		if(!isset($data['dates'][$sale->method])) {
			$data['dates'][$sale->method] = array();
		}
		if($date > 0) {
			// Setup date if needed
			if(!isset($data['dates'][$sale->method][$date])) {
				$data['dates'][$sale->method][$date]['sales'] = 0;
				$data['dates'][$sale->method][$date]['value'] = 0;
				$data['dates'][$sale->method][$date]['failed'] = 0;
				$data['dates'][$sale->method][$date]['expenses'] = 0;
			}
			if($sale->soldSuccess) {
				// Record Successful Sales
				$data['dates'][$sale->method][$date]['sales']++;
				$data['dates'][$sale->method][$date]['value'] += $sale->soldFor;			
				$data['totals']['sales'][$sale->method]++;
				$data['totals']['value'][$sale->method] += $sale->soldFor;				
			} else {
				// Record Failed Stats
				$data['dates'][$sale->method][$date]['failed']++;
				$data['totals']['sales'][$sale->method]++;
				$data['totals']['failed'][$sale->method]++;
			}
		} else {
			$data['totals']['pendingSales'][$sale->method]++;
			$data['totals']['pendingBuyout'][$sale->method] += $sale->buyout;
			$data['totals']['pendingBid'][$sale->method] += $sale->bid;
		}
	}
	if(isset($data['dates']['ah'])) {
		krsort($data['dates']['ah']);
	}
	if(isset($data['dates']['rmah'])) {
		krsort($data['dates']['rmah']);		
	}
	
	// $globalValue = 0;
	// $globalSales = 0;
	// foreach($this->allcompleted as $sale) {
	// 	if($sale->soldSuccess) {
	// 		// Record Successful Sales
	// 		$globalSales++;
	// 		$globalValue += $sale->soldFor;
	// 	}
	// }
	
	// var_dump($this->allSales->export()); exit;
	// var_dump($data['dates']); exit;
?>
<div id="summary-methods">
	<ul>
		<li><a href="#summary-ah">Battle.net - Gold AH</a></li>
		<li><a href="#summary-rmah">Battle.net - RMAH</a></li>
	</ul>
	<div id="summary-ah">		
		<?= $this->partial("./user/shop/_summary-table.phtml", array('data' => $data, 'type' => 'ah'))?>
	</div>
	<div id="summary-rmah">
		<?= $this->partial("./user/shop/_summary-table.phtml", array('data' => $data, 'type' => 'rmah'))?>		
	</div>
</div>
<script type="text/javascript">
	$("#summary-methods").tabs();
</script>
