<?php if ($this->pageCount > 1): ?>
<div id="guide-pagination">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
		<a href="?page=<?= $this->previous ?>">&lsaquo;</a>
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
		<?php if ($page != $this->current): ?>
			<a href="?page=<?= $page ?>" data-page="<?= $page ?>"><?php echo $page; ?></a>
		<?php else: ?>
			<span><?php echo $page; ?></span>
		<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
		<a data-page="<?= $page ?>" href="?page=<?= $this->next ?>">&rsaquo;</a>
	<?php endif; ?>
	<?php if (isset($this->last) && $this->last != $this->next && $this->last != $this->current): ?>
		<a data-page="<?= $page ?>" href="?page=<?= $this->last ?>">&raquo;</a>
	<?php endif; ?>
</div>
<?php endif; ?>