<div id="guide">
	<div class="title-block">
		<h1>Unpublishing your Guide</h1>
		<h2>
			<?= $this->mLink($this->guide) ?>
		</h2>
		<h5>
			By <span class='author'><?= $this->guide->author->username ?></span>
			on <span class='date'><?= date('F j, Y', $this->guide->_created) ?></span>
			<? if($this->guide->_updated): ?>
			 <br/>Last Updated: <span class='date'><?= date('F j, Y', $this->guide->_updated) ?></span>
			<? endif ?>
		</h5>
	</div>
	<div class="section">
		<h3>Are you sure you want to unpublish this guide?</h3>
		<div class="section-content">
			<p>By unpublishing this guide, you will make it so that the <strong>ONLY</strong> way to find this guide will be by visiting the URL directly. It will no longer show up on the homepage or any other page on D3Up.com</p>
			<p>You do <strong>not</strong> need to publish your guide in order to share it with others, other users can still access your guide if you send them a link.</p>
			<a href="?confirm=true" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" style="padding: 10px">Yes, unpublish my guide.</a>
		</div>
	</div>
</div>