<?
	$isOwner = ($this->guide->author->id === $this->profile->id);
?>
	
<style type="text/css" media="screen">
	#toolbar {
		border: 1px solid #333;
		background: #111;
		text-align: center;
		width: 960px;
		padding-bottom: 5px;
	}
	#toolbar h2 {
		margin: 0;
	}
	#toolbar.sticky {
		text-align: center;
		position: fixed;
		top: 0;		
	}
	.ui-button {
		border: 1px solid #000;
		-webkit-touch-callout: none;
		-webkit-user-select: none;
		-khtml-user-select: none;
		-moz-user-select: none;
		-ms-user-select: none;
		user-select: none;
	}
	#guide .content {
		border: 2px solid #000;
		font: normal 14px/1.3 Arial, sans-serif;
		line-height: 1.8em;
	}
	.section {
		border-top: 2px solid #000;
		padding: 0 20px 20px;
		background-image: -ms-linear-gradient(bottom, #111111 0%, #111111 70%, #333333 100%);
		background-image: -moz-linear-gradient(bottom, #111111 0%, #111111 70%, #333333 100%);
		background-image: -o-linear-gradient(bottom, #111111 0%, #111111 70%, #333333 100%);
		background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, #111111), color-stop(0.7, #111111), color-stop(1, #333333));
		background-image: -webkit-linear-gradient(bottom, #111111 0%, #111111 70%, #333333 100%);
		background-image: linear-gradient(to top, #111111 0%, #111111 70%, #333333 100%);
	}
	.section:first-child {
		border-top: 2px solid #333;
	}
	.section h3 {
		font-size: 1.5em;
		margin: 15px 0;
		padding: 0 15px;
		color: #B18135;
	}
	.section-control {
		margin: 5px;
		float: right;
	}
</style>
<? if($isOwner): ?>
<div id="toolbar">
	<div id="guide-owner">
		<h2>Guide Owner Tools</h2>
		<div class="control">
			<a style="padding: 5px 20px" class="createSection ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Add Section to Guide</a>
			<a style="padding: 5px 20px" class="saveGuide ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Save Sections</a>
			<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/edit" style="padding: 5px 20px; color: #fff" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Edit Title</a>
		</div>
	</div>
</div>
<form method="post" id="guide-form">
<? endif ?>
	<div id="guide" <?= ($isOwner) ? "data-owner='true'" : "" ?>>
		<div class="title">
			<img src="/images/<?= $this->guide->class ?>.png"/>		
			<h1><?= $this->guide->title ?></h1>
			<h2>
				<? if($this->guide->class): ?>
					<?= ucwords(str_replace("-", " ", $this->guide->class)) ?>
				<? endif ?>
				<?= $this->guideTopic($this->guide->topic) ?>
			</h2>
			<h5>
				By: <?= $this->guide->author->username ?>
				on <?= date('F j, Y', $this->guide->_created) ?>
				<? if($this->guide->_updated): ?>
				 (Updated: <?= date('F j, Y', $this->guide->_updated) ?>)
				<? endif ?>
			</h5>
		</div>
		<ul class="contents <?= $this->guide->class ?>">
			<? if($this->guide->sections): ?>
				<? foreach($this->guide->sections as $key => $section): ?>
					<li><a href="#<?= $key ?>"><?= $section->title ?></a></li>
				<? endforeach ?>
			<? endif ?>
		</ul>
		<div class="content">
			<? if($this->guide->sections): ?>
				<? foreach($this->guide->sections as $key => $section): ?>
				<div class="section">
					<h3 class="section-header"><?= $section->title ?></h3>
					<div class="section-content">
						<?= $section->content ?>
					</div>
				</div>
				<? endforeach ?>
			<? endif ?>
		</div>
	</div>
	<? if($isOwner): ?>
</form>
<script type="text/javascript" src="/js/guide.js"></script>
<? endif ?>