<link rel="stylesheet" href="/css/jquery.cleditor.css" type="text/css" />
<?
	$profile = Epic_Auth::getInstance()->getProfile();
	$isOwner = ($this->profile && $this->guide->author->id === $this->profile->id);
	$this->headTitle($this->guide->title); 
	if($this->guide->class) {
		$this->headTitle(ucwords(str_replace("-", " ", $this->guide->class)) . " Guide"); 		
	}
?>
<? if($isOwner): ?>
<div id="toolbar">
	<div id="guide-owner">
		<div class="controls" style="text-align: right; padding: 5px">
			<p>
				Status: <span id="save-status" class="true">Saved</span><br/>Published: <span id="publish-status" class="<?= ($this->guide->published) ? 'true' : 'false' ?>"><?= ($this->guide->published) ? 'Yes' : 'No' ?></span>
			</p>
		</div>
		<h2>Guide Owner Tools</h2>
		<div class="control">
			<a class="createSection ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Create Section</a>
			<? if($this->guide->published): ?>
				<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/unpublish" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Unpublish</a>
			<? else: ?>
				<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/publish" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Publish</a>
			<? endif ?>
			<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/edit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Edit Title</a>
			<a class="saveGuide ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Save</a>
			<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Cancel</a>
			<a href="/guide/<?= $this->guide->id ?>/<?= $this->guide->slug ?>/revisions" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" role="button">Revisions</a>
		</div>
		<div class="sub-control">
			<a href="#" id="minAll">Minimize All Sections</a>
		</div>
	</div>
</div>
<form method="post" id="guide-form">
<? endif ?>
	<div id="guide" class="content-page" <?= ($isOwner) ? "data-owner='true'" : "" ?> data-class="<?= $this->guide->class ?: 'all' ?>">
		<div class="title-block">
			<div id="social-share">
				<script type="text/javascript" src="http://www.reddit.com/static/button/button3.js"></script>
			</div>
			<div id="ratings-display">
				<div class='item-stat inline-flow'>
					<span class='value'><?= $this->prettyStat($this->guide->views) ?></span>
					<span class='stat'>Views</span>
				</div>
				<img id="button-upvote" src="/images/upvote.png" class="ui-state-disabled ui-corner-all" data-name="Guide Voting	" data-tooltip="In order to record your vote, we require to to be logged in. Please login or create an account!">
				<div class='item-stat inline-flow'>
					<span class='value' id="vote-count" data-count="<?= $this->guide->votes ?: 0 ?>"><?= $this->guide->votes ?: 0 ?></span>
					<span class='stat'>Votes</span>
				</div>
				<img id="button-downvote" src="/images/downvote.png" class="ui-state-disabled ui-corner-all" data-name="Guide Voting	" data-tooltip="In order to record your vote, we require to to be logged in. Please login or create an account!">
			</div>
			<h1><?= $this->guide->title ?></h1>
			<h2>
				<? if($this->guide->class): ?>
					<?= ucwords(str_replace("-", " ", $this->guide->class)) ?>
				<? endif ?>
				<?= $this->guideTopic($this->guide->topic) ?>
			</h2>
			<h5>
				By <span class='author'><?= $this->guide->author->username ?></span>
				on <span class='date'><?= date('F j, Y', $this->guide->_created) ?></span>
				<? if($this->guide->_updated): ?>
				 <br/>Last Updated: <span class='date'><?= date('F j, Y', $this->guide->_updated) ?></span>
				<? endif ?>
			</h5>
		</div>
		<div class="toc section">
			<h3>Contents of this Guide</h3>
			<ul id="toc" class="contents <?= $this->guide->class ?>">
				<? if($this->guide->sections): ?>
					<? foreach($this->guide->sections as $key => $section): ?>
						<li data-section="<?= $key ?>"><a href="#section-<?= $key ?>"><?= $section->title ?></a></li>
					<? endforeach ?>
				<? else: ?>
					<li>This guide has no content yet!</li>
				<? endif ?>
			</ul>
		</div>
		<div class="content">
			<? if($this->guide->sections): ?>
				<? foreach($this->guide->sections as $key => $section): ?>
					<? if(!$section->hidden || $isOwner): ?>
					<div id="section-<?= $key ?>" class="section" data-section="<?= $key ?>" data-section-type="<?= $section->type ?: 'generic' ?>" data-hidden="<?= $section->hidden ?>">
						<?= $this->partial("./guide/sections/".($section->type?:'generic').".phtml", array('section' => $section)) ?>
					</div>
					<? endif ?>
				<? endforeach ?>
			<? endif ?>
		</div>
	</div>
	<? if($isOwner): ?>
</form>
<? endif ?>
<script>
if(!window.d3up) {
	window.d3up = {};
}

<? if($profile): ?>
window.d3up['isLoggedIn'] = true;
<? else: ?>
window.d3up['isLoggedIn'] = false;
<? endif ?>

<? if($this->alreadyVoted): ?>
window.d3up['voted'] = '<?= $this->alreadyVoted ?>';
<? else: ?>
window.d3up['voted'] = false;
<? endif ?>

</script>

<script type="text/javascript" src="/js/jquery.cleditor.js"></script>
<script type="text/javascript" src="/js/unmin/guide.js?v=<?= time() ?>"></script>

<div id="disqus_thread" class='section' style='padding: 10px'></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'd3up'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
