<h1>Gear Based DPS Calculations</h1>
<p>Updated: Jul 26, 2012</p>
<p>The gear based DPS calculations are calculated by comparing your DPS while wearing all of your gear, then determining what you would lose if you were to completely remove that piece. For example: </p>
<pre>30,000 DPS w/ Full Gear - 25,000 DPS w/ Full Gear (Minus the Selected Piece) = 5,000 Gear DPS Contribution</pre>
<p>It is done for each piece of gear you are wearing and displayed on the Gear DPS Contributions section of the DPS tab.</p>
<p>If you have a better method, feel free to <a href="mailto:aaron.cox@greymass.com">email me!</a></p>