<h1>My Shop - Item Pricer</h1>
<p>Updated: Jul 31, 2012</p>
<p>The price checker tool is a highly experimental tool designed to help you find similar items and gauge how much to price them for.</p>
<p>To use the tool, select the type of item from the drop down menu, and add any attributes the item may have.</p>
<h3>How Stat Searching works...</h3>
<p>Stats are the major calculated numbers at the top of the item such as Armor, Block Chance, DPS and the Damage Range.</p>
<ul>
	<li>Searching for stats will search for +/- 20 of the stats you indicate.</li>
	<li>Leaving the Stat text boxes empty will not search for that stat.</li>
</ul>
<h3>How Attribute Searching works...</h3>
<p>Attributes are the blue statistics on the item such as Dexterity, Vitality, Resist All or Magic Find.</p>
<ul>
	<li>Putting any number in the attribute text box will search for items +/- 10% of that attributes maximum value (rating).</li>
	<li>Putting "0" or leaving an attribute text box empty indicates you want an item where that stat exists.</li>
</ul>
<h3>Search Results</h3>
<p>The search results loaded into the right pane will show the name, have a tooltip, the price (<span class='pos'>green</span> for sold, <span class='neg'>red</span> for unsold) and the date it was sold on.</p>
<h3>Known Issues...</h3>
<ul>
	<li>Changing the Item's Type resets the Stats values.</li>
	<li>You currently have to specify which KIND of weapon you want to search for, I'll add "slot type" soon.</li>
	<li>Searching by Block Chance and Block Values on shields is not functional.</li>
</ul>