<h5><a href="/" class="drop">My D3Up.com</a></h5>
<span><a href="/" class="drop">Builds, Guides and Items</a></span>
<div class="dropdown_3columns">
	<div class="col_1">
		<h2 style="margin-bottom: 0">Quick Access</h2>
	</div>
	<div class="col_1">
		<h2>Builds</h2>
	</div>
	<div class="col_1">
		<h2>Guides</h2>
	</div>
	<div class="col_1">
		<p><a class="button" href="/user/builds">Builds</a></p>
		<p><a class="button" href="/user/guides">Guides</a></p>
		<p><a class="button" href="/user/items">Items</a></p>
		<p><a class="button" href="/user/edit">Profile</a></p>
		<p><a class="button" href="/user/logout">Logout</a></p>
	</div>
	<div class="col_1">
		<? if(count($this->userBuilds)): ?>
		<ul class="dropdown_links">
			<? foreach($this->userBuilds as $build): ?>
			<li><?= $this->mLink($build) ?></li>
			<? endforeach ?>
		</ul>
		<? else: ?>
		<p class="notice">You don't have any builds!</p>
		<p><a class="button" href="/build/create">Create a Build</a></p>
		<? endif ?>
	</div>
	<div class="col_1">
		<? if(count($this->userGuides)): ?>
		<ul class="dropdown_links">
			<? foreach($this->userGuides as $guide): ?>
			<li><?= $this->guideLink($guide) ?></li>
			<? endforeach ?>
		</ul>
		<? else: ?>
		<p class="notice">You don't have any guides!</p>
		<p><a class="button" href="/guide/create">Create a Guide</a></p>
			<? endif ?>
	</div>
</div>