<h5><a href="/" class="drop">My D3Up.com</a></h5>
<span><a href="/" class="drop">Builds, Guides and Items</a></span>
<div class="dropdown_3columns">
	<div class="col_1 col_first">
		<h2 style="margin-bottom: 0">Quick Access</h2>
	</div>
	<div class="col_2">
		<h2>My Builds</h2>
	</div>
	<div class="col_1 col_first">
		<p><a class="button" href="/user/builds">My Builds</a></p>
		<p><a class="button" href="/user/guides">My Guides</a></p>
		<p><a class="button" href="/user/items">My Items</a></p>
		<p><a class="button" href="/user/edit">My Profile</a></p>
		<p><a class="button" href="/user/logout">Logout</a></p>
	</div>
	<div class="col_2">
		<? if(count($this->userBuilds)): ?>
		<ul class="dropdown_links">
			<? foreach($this->userBuilds as $build): ?>
			  <li class="build <?= $build->class ?>"><?= $this->mLink($build, array("text" => $build->name . "<br/><span class='level'>Level ".($build->level?:60)."</span>, Paragon <span class='paragon'>".($build->paragon?:0)."</span>")) ?></li>
			<? endforeach ?>
		</ul>
		<a class='button' href="/build/create">Create New Build</a>
		<? else: ?>
		<p class="notice">You don't have any builds!</p>
		<p><a class="button" href="/build/create">Create a Build</a></p>
		<? endif ?>
	</div>
</div>