<?
	$profile = Epic_Auth::getInstance()->getProfile();
	$this->headTitle($this->record->name); 
	$this->headTitle(ucwords(str_replace("-", " ", $this->record->class))); 
	$myBuild = false;
	if($profile && $this->record->_createdBy && $profile->createReference() == $this->record->_createdBy->createReference()) {
		$myBuild = true;
	}	
?>
<script type="text/javascript">
<? if($this->record->passives && $this->record->passives != "null" && count($this->record->passives)): ?>
var activePassives = <?= json_encode($this->record->passives->export()); ?>;
<? else: ?>
var activePassives = [];
<? endif; ?>
<? if($this->record->actives && $this->record->actives != "null" && count($this->record->actives)): ?>
var activeActives = <?= json_encode($this->record->actives->export()); ?>;
<? else: ?>
var activeActives = [];
<? endif; ?>
</script>

<? if($profile && $this->record->_createdBy): ?>
<div class="controls">
	<? if($profile->createReference() == $this->record->_createdBy->createReference()): ?>
		<a href="/b/<?= $this->record->id ?>/edit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">Edit</span></a>			
	<? else: ?>
		<a href="/b/<?= $this->record->id ?>/copy" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">Copy this Build</span></a>
	<? endif; ?>
</div>
<? endif; ?>

<h2 class="table-header">
	<?= $this->record->name ?> (<?= ucwords(str_replace("-", " ", $this->record->class)) ?>)
</h2>

<div id="skill-display" class="build-header ui-widget ui-corner-all" >
	<ul id="active-display">
		<li>No Passives Selected</li>
	</ul>
	<ul id="passive-display">
		<li>No Passives Selected</li>
	</ul>
</div>

<div id="character" class="inline-flow" data-class="<?= $this->record->class ?>" <? if($myBuild) { echo "data-owner='true'"; } ?>>
	<ul>
		<li><a href="#build-gear">Gear</a></li>
			<li><a href="#build-skills">Skills</a></li>
		<? if($myBuild): ?>
			<li><a href="#build-compare">Compare</a></li>
			<li><a href="#item-simulate">Simulate Item</a></li>
		<? endif ?>
		<? if($this->record->guideIsPublished || $myBuild): ?>
			<li><a href="#build-guide">Guide</a></li>
		<? endif ?>
		<!-- <li><a href="#">Comments</a></li> -->
	</ul>
	<div id="build-skills">
		<h3>Character Skills/Passives</h3>
		<div <?= (!$myBuild) ? "style='display: none'" : ""?>>
			<select id="passives" multiple="multiple" name="passives[]" style="width: 450px" data-placeholder="Choose the Passives you use"></select>
			<select id="actives" multiple="multiple" name="actives[]" style="width: 450px" data-placeholder="Choose the Skills you use"></select>
		</div>
		<ul id='build-active-skills'></ul>
		<ul id='build-passive-skills'></ul>
	</div>
	<? if($this->record->guide || $myBuild): ?>
		<div id="build-guide">
			<? if($myBuild): ?>
				<p>You may build a guide to help explain this build using the textbox below. Guides may be created using <a href="http://en.wikipedia.org/wiki/Markdown#Syntax_examples">Markdown Syntax</a> and limited HTML tags similar to sites such as <a href="http://reddit.com">Reddit</a>.</p>
				<p><strong>NOTE:</strong> The GUIDE tab on your build will not be publicly available until you check the "Publish" checkbox and hit save at the bottom of the form.</p>
				<?= $this->guideForm ?>
				<p>Shown below is how your guide appears:</p>
				<hr/>
			<? endif ?>
			<? if($this->record->guide && $this->record->guideIsPublished): ?>
				<?= $this->record->guide ?>
			<? endif ?>
		</div>
	<? endif ?>
	<? if($myBuild): ?>
	<div id="item-simulate">
		<p>Which item do you wish to simulate changes on?</p>
		<p><select id="simulate-slot">
			<option></option>
			<? foreach($this->record->equipment->getSlots() as $slot): ?>
				<option class="slot" value="<?= $slot ?>"><?= ucfirst($slot) ?></option>
			<? endforeach; ?>
		</select></p>
		<p><span id="simulate-against"></span></p>
		<div id="simulation-stats">
			<p>Loaded below are the stats currently on the item, feel free to adjust them to see the changes live in your build as well as a table of differences that's automatically generated below.</p>
			<p>Attributes</p>
			<select id="simulate-attributes" data-placeholder="Select Attributes for Item" multiple="multiple" style="width: 510px">
				<?= $this->render("./item/_itemAttributeOptions.phtml") ?>
				<option value="armor" label="+ Armor">+ Armor</option>
			</select>
			<div id="simulate-stats" class="d3-item">
				<div class="top"><p class="">Name</p></div>
				<div class="item">
					<p class="stats stats-primary">
						<span class="big-stat"></span>
						<span class="stat-helper"></span>
					</p>
					<p class="stats stats-extra-percent"></p>
					<p class="stats stats-extra-range"></p>
					<ul class="attrs">
					</ul>
					<ul class="sockets">
					</ul>
				</div>
				<div class="bottom"> 
					<? if($profile = Epic_Auth::getInstance()->getProfile()): ?>
						Created by: <?= $profile->username ?>
					<? endif; ?>
				</div>
			</div>
			<div class="compare-diff"></div>
			<p>Please note: When working with a weapon, the +% Damage, +Elemental Damage, +% Speed and other attributes don't matter. The only things that matter are the Min/Max damage and Attacks per Second (Obviously Primary Stats, Crit, etc all still matter).</p>
		</div>
	</div>
	<div id="build-compare">
		<p>This compare tool will compare what you are <b>currently wearing</b> to an item you select from the database.</p>
		<p>Please select the <i>slot</i> of the item you wish to compare first, then select the item from your items from the drop down.</p>
		<p>Which item slot should we compare?</p>
		<select id="compared-slot">
			<option></option>
			<? foreach($this->record->equipment->getSlots() as $slot): ?>
				<option class="slot" value="<?= $slot ?>"><?= ucfirst($slot) ?></option>
			<? endforeach; ?>
		</select>
		<span id="compared-to"></span>
		<p>And what should we compare it to?</p>
		My Items: 
		<select id="compare-to">
		</select>
		<!-- or
		<input type="text" id="compare-to-id" style="width: 50px"/> (Enter Item ID) -->
		<ul id="compare-notes"></ul>
		<div class="compare-diff"></div>
		<p><b>Note</b>: Currently the item HAS to be created by you before you are able to compare them.</p>
	</div>
	<? endif; ?>
	<div id="build-gear">
		<? if($myBuild): ?>
		<p>Adding gear to your build will dynamically update the statistics displayed in the statistics panel.</p>
		<p>
			<a href="/item/create" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">Create New Item</span></a>
			<a href="/user/items" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">View My Items</span></a>
		</p>
		<? endif; ?>
		<table class="equipment-table">
		<? foreach($this->record->equipment->getSlots() as $slot): ?>
			<tr>
				<td>
					<?= ucfirst($slot) ?>
				</td>
				<? if($myBuild): ?>
				<td>
					<button id="change-<?= $slot ?>" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change" data-item-type="<?= $slot ?>" role="button" aria-disabled="false"><span class="ui-button-text">Change</span></button>
					<a id="new-<?= $slot ?>" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" href="/item/create?b=<?= $this->record->id ?>&slot=<?= $slot ?>&return=build"><span class="ui-button-text">New</span></a>
				</td>
				<? endif; ?>
				<td class="primary">
					<span class="equipped" id="equipped-<?= $slot ?>" data-slot="<?= $slot ?>">
						<? if($this->record->equipment[$slot]->id): ?>
							<?= $this->itemLink($this->record->equipment[$slot]) ?>
						<? else: ?>
							Nothing
						<? endif ?>
					</span>
				</td>
			</tr>
		<? endforeach ?>
		</table>
	</div>
	<? if($this->comments): ?>
	<div id="build-comments" style="display: none">
		<?= $this->commentForm ?>
		<hr/>
		<? foreach($this->comments as $comment): ?>
			<div class='comment' id="comment-<?= $comment->id ?>" data-comment="<?= $comment->id ?>">
				<div class='comment-meta'>
					<span class='comment-author'><?= $comment->profile->username?:'Anonymous' ?></span> - 
					<span class='comment-time'>
						<?= $this->timeAgo($comment->_created) ?>
					</span>
				</div>
				<div class='comment-body'>
					<?= $comment->body ?>
				</div>
				<div class='comment-buttons'>
					<a href="#">permalink</a>
					<a class='comment-reply'>reply</a>
				</div>
				<div class='comment-extra'></div>
				<div class="comment-replies">
				<? foreach($comment->getReplies() as $reply): ?>
					<div class='comment reply' id="comment-<?= $reply->id ?>" data-comment="<?= $reply->id ?>">
						<div class='comment-meta'>
							<span class='comment-author'><?= $comment->profile->username?:'Anonymous' ?></span> - 
							<span class='comment-time'>
								<?= $this->timeAgo($reply->_created) ?>
							</span>
						</div>
						<div class='comment-body'>
							<?= $reply->body ?>
						</div>
					</div>
				<? endforeach ?>
				</div>
			</div>
		<? endforeach ?>
	</div>
	<? endif; ?>
</div>
<div class="inline-flow" style="width: 396px">
	<div class="calc-stats ui-widget ui-widget-content ui-corner-all">
		<ul>
			<li><a href="#tab-base">Stats</a></li>
			<li><a href="#tab-dps">DPS</a></li>
			<li><a href="#tab-ehp">EHP</a></li>
		</ul>
		<div style="background-image: none; padding: 15px 15px 0">
			<select id="vsLevel">
				<option value="60" selected="selected">Stats vs Level 60 Monster</option>
				<option value="61">Stats vs Level 61 Monster</option>
				<option value="62">Stats vs Level 62 Monster</option>
				<option value="63">Stats vs Level 63 Monster</option>
			</select>
		</div>
		<div id="tab-base">
			<ul id="stats-offense"><li>Damage</li></ul>
			<ul id="stats-base"><li>base</li></ul>
			<ul id="stats-life"><li>life</li></ul>
			<ul id="stats-defense"><li>armor</li></ul>
			<ul id="stats-misc"></ul>
		</div>
		<div id="tab-dps">
			<ul id="stats-dps-gear"><li>test</li></ul>
		</div>
		<div id="tab-ehp">
			<ul id="stats-ehp"><li>test</li></ul>
			<ul id="stats-ehp-gear"></ul>
		</div>
	</div>
</div>
<div id="gear-change" title="Select an Item">
	<p>Listed below are all of the items you've created that would fit into this equipment slot.</p>
	<p>Please choose which item you'd like to equip.</p>
	<fieldset>
		<select name="available" id="available-gear" class="ui-widget-content ui-corner-all">
		</select>
	</fieldset>
	</form>
</div>
<script type="text/javascript" src="/js/unmin/skills.js?time=<?= time() ?>"></script>
<script type="text/javascript" src="/js/unmin/calcv2.js?time=<?= time() ?>"></script>
<script type="text/javascript" src="/js/unmin/build.js?time=<?= time() ?>"></script>