<h2 class="table-header">Battle.net Profile Crawler</h2>
<? if($this->status): ?>
	<div class="ui-widget ui-corner-all ui-widget-content ui-helper-clearfix" style="padding: 0 20px">
		<h3>Crawl Results</h3>
		<p>All character stats are based on level 60 characters currently, so if you import a character that is not level 60, the calculator will be slightly off.</p>
		<p>Paragon Levels are also not automatically imported! To change your paragon level, please hit "Edit" on the top of your build page and enter it in the appropriate field.</p>
		<p>This process is still somewhat buggy, please report anything that seems wrong using the feedback tab on the side or you can email me directly at <a href="mailto:aaron.cox@greymass.com">aaron.cox@greymass.com</a>. Please include a link to your D3Up build and what isn't working correctly so I can check it out from there!</p>
		<p>
			<a href="/b/<?= $this->record->id ?>" class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' style="padding: 5px; width: 450px">Goto my Build</a>
		</p>
		<table class='d3up-table'>
			<tr>
				<th>Slot</th>
				<th>Item Name</th>
				<th>Results</th>
			</tr>
		<? foreach($this->status as $status): ?>
			<tr>
				<td><?= $status['slot'] ?></td>
				<td><?= $this->itemLink($status['item']) ?></td>
				<td>
					<? if($status['result'] == "new"): ?>
						Created New Item
					<? endif ?>
					<? if($status['result'] == 'existed'): ?>
						Already Existed, Equipped
					<? endif ?>
				</td>
			</tr>
		<? endforeach ?>
		</table>
	</div>
<? else: ?>
	<div class="ui-widget ui-corner-all ui-widget-content ui-helper-clearfix" style="padding: 20px">
		<h2 style="color: #00C800">Battle.net Character Copy</h2>
		<p>You've chosen to import a character from the Diablo 3 Armory into this build:</p>
		<h2>Build #<?= $this->record->id ?> - <?= $this->mLink($this->record) ?></h2>
		<p><strong>PLEASE NOTE</strong>, none of your items will be deleted, but they will un-equipped and the proper gear from your Diablo 3 Armory profile will be equipped to your build. It will also change the skills on your build to match the armory.</p>
		<p>Please select which character's gear and skills we should import into <?= $this->mLink($this->record)?>.</p>
		<table id="all-builds" class="d3up-table">
			<thead>
				<th></th>
				<th>Name</th>
				<th>Class</th>
				<th>Level</th>
				<th>Mode</th>
				<th>Actions</th>
			</thead>
			<tbody>
				<? foreach($this->characters as $character): ?>
				<tr class='build-row'>
					<td class="icon"><img src="/images/<?= $character['class'] ?>.png"/></td>
					<td><?= $character['name'] ?></td>
					<td><?= ucwords(str_replace("-", " ", $character['class'])) ?></td>
					<td>Level <?= $character['level'] ?></td>
					<td>
						<? if($character['hardcore']): ?>
							Hardcore
						<? else: ?>
							Softcore
						<? endif ?>
					</td>
					<td>
						<a href="?character=<?= $character['id'] ?>" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only"><span class="ui-button-text">Copy this Character</span></a>
					</td>
				</tr>
				<? endforeach ?>
			</tbody>
		</table>
	</div>
<? endif ?>