<div class="ui-widget ui-corner-all ui-widget-content" style="padding: 20px">
	<div style="float: right">
		<?= $this->displayItem($this->record) ?>
	</div>
	<h2 style="color: #C80000">Are you sure you want to delete this?</h2>
	<p style="font-size: 1.2em; line-height: 1.6em">Deleting this will not actually delete the it completely, it will just remove it from the list of your things. You'll be able to find it again by searching or save this link for future reference:</p>
	<?
		if($this->record->_type == "item") {
			$link = "/i/".$this->record->id;
		}
	?>
	<input type="text" value="http://d3up.com<?= $link ?>" style="width: 300px"/>
	<p>
		Please confirm your choice:
	</p>
	<p>
		<a href="?confirm=true" class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' style="padding: 5px; width: 450px">Yes, remove this</a>
	</p>
	<p>
		<a href="/user/items" class='ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only' style="padding: 5px; width: 450px">No, keep it</a>
	</p>
</div>