<style type="text/css" media="screen">
	.single-item {
		width: 430px;
		margin: 20px auto;
	}
</style>
<div class="single-item">
	<?= $this->displayItem($this->record) ?>
	<p style='text-align: center'>
		Link: <input type='text' value='http://d3up.com<?= $this->url(array('record' => $this->record), $this->record->route, true) ?>'/>
		<a href="/i/<?= $this->record->id ?>/edit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">Edit</span></a>
	</p>
	<p>Text Version of the Item:
<? $p = new D3Up_View_Helper_DisplayItem() ?>
<textarea style="text-align: left; width: 425px; height: 200px">
<?= $this->record->name?> (<?= $p->_qualityMap[$this->record->quality] ?> <?= $p->prettyDisplay($this->record->type) ?>)
<? if(isset($this->record->stats['dps'])): ?>
<?= $this->record->stats['dps'] ?> dps
<?= implode("-", $this->record->stats['damage']->export()) ?> damage
<?= $this->record->stats['speed'] ?> attack speed
<? elseif(isset($this->record->stats['armor'])): ?>
<?= $this->record->stats['armor']?> Armor
<? if(isset($this->record->stats['block-chance'])):?>
+<?= $this->record->stats['block-chance']?>% Block Chance
<?= implode("-", $this->record->stats['block-amount']->export()) ?> Block Amount
<? endif?>
<? endif; ?>
<? if($this->record->attrs): ?>
<? foreach($this->record->attrs as $k => $v): ?>
<?= $p->prettyDisplay($k, $v) ?> 
<? endforeach ?>
<? endif; ?>
<? if($this->record->sockets): ?>
<? foreach($this->record->sockets as $k => $v): ?>
<? if($v == null): ?>
[Empty Socket]
<? else: ?>
[Socket] <?= ucwords(str_replace("_"," ", $v)) ?> (<?= $p->gemEffect($v, $this->record->type) ?>)
<? endif; ?>
<? endforeach ?>
<? endif; ?>
</textarea>
	</p>
</div>