<?
	$profile = Epic_Auth::getInstance()->getProfile();
	$this->headTitle($this->record->name); 
?>
<style type="text/css" media="screen">
	.single-item {
		width: 430px;
		margin: 20px auto;
	}
</style>
<div class="single-item">
	<?= $this->displayItem($this->record) ?>
	<? if($this->record->rating): ?>
	<div style="background-color: #111; margin: 5px; padding: 5px" class='ui-widget ui-corner-all'>
	<h3 style="margin: 0">Perfection Ratings</h3>
	<table class="perfection-rating">
		<tr>
			<? foreach($this->record->rating as $key => $value): ?>
				<? if($key == 'total') { continue; } ?>
				<td><?= $this->itemStat($key, round($value, 1) . "%", $value)?></td>
			<? endforeach ?>			
			<td>
				<?= $this->itemStat('total', $this->record->rating['total']."%", $this->record->rating['total'])  ?>
			</td>
		</tr>
	</table>
	</div>
	<? endif ?>
	<p style='text-align: center'>
		Link: <input type='text' value='http://d3up.com<?= $this->url(array('record' => $this->record), $this->record->route, true) ?>'/>
		<? if($profile && $this->record->_createdBy && $profile->createReference() == $this->record->_createdBy->createReference()): ?>
		<a href="/i/<?= $this->record->id ?>/edit" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text">Edit</span></a>
		<? endif; ?>
		<? if($profile && $this->record->_createdBy && $profile->createReference() != $this->record->_createdBy->createReference()): ?>
		<a href="/i/<?= $this->record->id ?>/copy" class="has-tooltip ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only gear-change"><span class="ui-button-text" data-tooltip="Copy this item into 'My Items'">Make a Copy</span></a>
		<? endif; ?>
	</p>
	<p>Text Version of the Item:
<? $p = new D3Up_View_Helper_DisplayItem() ?>
<textarea style="text-align: left; width: 425px; height: 200px">
<?= $this->record->name?> (<?= $p->_qualityMap[$this->record->quality] ?> <?= $p->prettyDisplay($this->record->type) ?>)
<? if(isset($this->record->stats['dps'])): ?>
<?= $this->record->stats['dps'] ?> dps
<?= implode("-", $this->record->stats['damage']->export()) ?> damage
<?= $this->record->stats['speed'] ?> attack speed
<? elseif(isset($this->record->stats['armor'])): ?>
<?= $this->record->stats['armor']?> Armor
<? if(isset($this->record->stats['block-chance'])):?>
+<?= $this->record->stats['block-chance']?>% Block Chance
<?= implode("-", $this->record->stats['block-amount']->export()) ?> Block Amount
<? endif?>
<? endif; ?>
<? if($this->record->attrs): ?>
<? foreach($this->record->attrs as $k => $v): ?>
<?= $p->prettyDisplay($k, $v) ?> 
<? endforeach ?>
<? endif; ?>
<? if($this->record->sockets): ?>
<? foreach($this->record->sockets as $k => $v): ?>
<? if($v == null): ?>
[Empty Socket]
<? else: ?>
<? $effect = $p->gemEffect($v, $this->record->type);?>
[Socket] <?= ucwords(str_replace("_"," ", $v)) ?> (<?= $p->prettyDisplay($effect[0], $effect[1]) ?>)
<? endif; ?>
<? endforeach ?>
<? endif; ?>
</textarea>
	</p>
</div>