<div class="menu-bar">
	<div class="menu-wrap">
		<ul id="megamenu" class="ui-helper-clearfix">
			<li>
				<? if($this->profile): ?>
					<?= $this->render("menu/user.phtml") ?>
				<? else: ?>
					<?= $this->render("menu/nouser.phtml") ?>
				<? endif ?>
			</li>
			<li>
				<h5><a href="/guide" class="drop">Guides</a></h5>
				<span><a href="/guide" class="drop">Diablo 3 Guides</a></span>
	      <div class="dropdown_3columns">
					<div class="col_2">
						<h3>Class Guides</h3>
						<ul class="dropdown_links">
							<li class='barbarian'><a href="/guide?class=barbarian">Barbarian Guides</a></li>
							<li class='demon-hunter'><a href="/guide?class=demon-hunter">Demon Hunter Guides</a></li>
							<li class='monk'><a href="/guide?class=monk">Monk Guides</a></li>
							<li class='witch-doctor'><a href="/guide?class=witch-doctor">Witch Doctor Guides</a></li>
							<li class='wizard'><a href="/guide?class=wizard">Wizard Guides</a></li>
						</ul>   
					</div>
					<div class="col_1">
						<h3>Guides Types</h3>
						<ul class="dropdown_links">
							<li><a href="/guide?type=general">General</a></li>
							<li><a href="/guide?type=class">Class</a></li>
							<li><a href="/guide?type=farming">Farming</a></li>
							<li><a href="/guide?type=leveling">Leveling</a></li>
							<li><a href="/guide?type=pvp">PVP</a></li>
						</ul>   
					</div>
					<div class="col_3">
						<h3>Want to share your strategy?</h3>
						<div class="col_1" style="margin: 0 5px 0 0">
							<a class="button" href="/guide/create">Create a Guide</a>
						</div>
						<div class="col_2" style="margin: 0 5px 0 0">
							<p>Use D3Up.com's Guide Creator to share your ideas with content, images, game data and videos.</p>
						</div>
					</div>
	      </div>
			</li>
			<li>
				<h5><a href="/build" class="drop">Builds</a></h5>
				<span><a href="/build" class="drop">Class Builds</a></span>
				<div class="dropdown_3columns">
					<div class="col_2">
						<h3>By Class</h3>
						<ul class="dropdown_links">
							<li class='barbarian'><a href="/build?class=barbarian">Barbarian</a></li>
							<li class='demon-hunter'><a href="/build?class=demon-hunter">Demon Hunter</a></li>
							<li class='monk'><a href="/build?class=monk">Monk</a></li>
							<li class='witch-doctor'><a href="/build?class=witch-doctor">Witch Doctor</a></li>
							<li class='wizard'><a href="/build?class=wizard">Wizard</a></li>
						</ul>   
					</div>
					<div class="col_1">
						<h3>Search By</h3>
						<ul class="dropdown_links">
							<li><a href="/build?sort=dps">Overall DPS</a></li>
							<li><a href="/build?sort=ehp">Overall EHP</a></li>
						</ul>   
					</div>
					<div class="col_3">
						<h3>Want to create your own build?</h3>
						<div class="col_1" style="margin: 0 5px 0 0">
							<a class="button" href="/build/create">Create a Build</a>
						</div>
						<div class="col_2" style="margin: 0 5px 0 0">
							<p>Use D3Up.com's Build Creator to create a build from scratch or import your character directly from Battle.net!</p>
						</div>
					</div>
	      </div>
			</li>
			<li>
				<h5><a href="/items" class="drop">Items</a></h5>
				<span><a href="/items" class="drop">Item DB</a></span>
				<div class="dropdown_2columns">
					<div class="col_2">
						<ul class="dropdown_links">
							<? if($this->profile): ?>
								<li><a class="button" href="/user/items">My Items</a></li>
							<? endif ?>
							<li><a href="/user/shop">My Shop</a></li>
							<li><a href="/item/sales-history">Sales History</a></li>
							<li><a href="/item">All Items</a>
						</ul>   
						<a class='button' href="/item/create">Create New Item</a>
					</div>
	      </div>
			</li>
			<li>
				<h5><a href="/updates" class="drop">Updates</a></h5>
				<span><a href="/updates" class="drop">Site Patch Notes</a></span>
				<div class="dropdown_3columns align_right">
					<div class="col_3">
						<h2 style="border: 0; margin-bottom: 0">D3Up.com - News & Updates</h2>
					</div>
					<div class="col_2">
						<h3>Recent Updates</h3>
						<ul class="dropdown_links">
							<? foreach($this->navRecentNews as $news): ?>
								<li><a href="/update/<?= $news->id ?>">Version <?= $news->version ?></a></li>
							<? endforeach ?>
						</ul>   
					</div>
					<div class="col_1">
						<h3>Links</h3>
						<ul class="dropdown_links">
							<li><a href="/updates">All Updates</a></li>
						</ul>   
					</div>
	      </div>
			</li>
      <!-- <li>
        <h5><a href="/updates" class="drop">Help</a></h5>
        <span><a href="/updates" class="drop">FAQs & Info</a></span>
        <div class="dropdown_3columns align_right">
          <div class="col_3">
            <h2 style="border: 0; margin-bottom: 0">Diablo 3 Guides</h2>
          </div>
          <div class="col_1">
            <h3>Class Guides</h3>
            <ul class="dropdown_links">
              <li class='barbarian'><a href="/guide?class=barbarian">Barbarian</a></li>
              <li class='demon-hunter'><a href="/guide?class=demon-hunter">Demon Hunter</a></li>
              <li class='monk'><a href="/guide?class=monk">Monk</a></li>
              <li class='witch-doctor'><a href="/guide?class=witch-doctor">Witch Doctor</a></li>
              <li class='wizard'><a href="/guide?class=wizard">Wizard</a></li>
            </ul>   
          </div>
          <div class="col_1">
            <h3>Guides Types</h3>
            <ul class="dropdown_links">
              <li><a href="/guide?type=general">General</a></li>
              <li><a href="/guide?type=class">Class</a></li>
              <li><a href="/guide?type=farming">Farming</a></li>
              <li><a href="/guide?type=leveling">Leveling</a></li>
              <li><a href="/guide?type=pvp">PVP</a></li>
            </ul>   
          </div>
          <div class="col_1">
            <h3>More</h3>
            <ul class="dropdown_links">
              <li><a href="/guide/create">Create a Guide</a></li>
              <li><a href="#">Highest Voted</a></li>
              <li><a href="#">Most Viewed</a></li>
            </ul>   
          </div>
          <div class="col_3">
            <p>All the guides on D3Up.com are created by Diablo 3 players to help share successful strategies. Feel free to create your own guide if you'd like to share something you've discovered!</p>
          </div>
        </div>
      </li> -->
      <li class='social'>
        <a href="http://twitter.com/d3up"><img src='/images/t_logo.png'/></a>
      </li>
			<li class='social'>
			  <a href="http://facebook.com/d3upgrade"><img src='/images/f_logo.png'/></a>
			</li>
		</ul>	
	</div>
</div>