<div id="sys-message">
	<h3 style='margin: 0; color: #d00'>Server Updates - Restarting Services</h3>
	Afternoon of Nov 8th - I'll be doing some testing and updates on the server itself. 
	During this time, I'll be occasionally restarting some of the applications that run D3Up, so if something doesn't load, give it a second and try again.
	Please report any bugs via the feedback tab or email me at <a href="mailto:aaron.cox@greymass.com">aaron.cox@greymass.com</a>.
</div>
