<script type="text/javascript"><!--
google_ad_client = "ca-pub-2154138165823650";
/* D3Up.com - Leaderboard */
google_ad_slot = "8888964129";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>
<div class='ad-info'>
<!-- 	<span style="color: #0f0">Build browsing's re-enabled!</span> <a href='http://www.reddit.com/r/d3up/comments/1faauv/testing_some_ads_and_moving_out_west/'>Why is this ad here (Updated July 12th)?</a>. 
  
 -->
    <span style="color: #f00">Progress Report on RoS D3Up:</span> <a href='http://www.reddit.com/r/d3up/comments/22yzij/d3up_ros_updates_in_progress/'>Read the Updates & Post Bugs</a>.

Feel free to contact me at <a href="mailto:aaron.cox@greymass.com">aaron.cox@greymass.com</a>.
</div>