<!doctype html>
<head>
	<?= $this->headTitle("Diablo 3 Upgrade Calculator")->setSeparator(' | '); ?>
	<link rel="stylesheet" href="/css/jquery.dataTables.css" type="text/css" charset="utf-8">	
	<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.19/themes/dot-luv/jquery-ui.css" type="text/css" />
	<link rel="stylesheet" href="/css/style.css" type="text/css" charset="utf-8">	
	<link rel="stylesheet" href="/css/chosen.css" type="text/css" charset="utf-8">	
	<link rel="stylesheet" href="/css/tooltip.css" type="text/css" charset="utf-8">	
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>
	<script type="text/javascript" src="/js/chosen.jquery.js"></script>
	<script type="text/javascript" src="/js/site.js"></script>
	<script type="text/javascript" src="/js/tooltip.js"></script>
	<script type="text/javascript" src="/js/jquery.diff.js"></script>
	<script type="text/javascript" src="/js/jquery.dataTables.js"></script>
</head>
<body>
	<div id="wrapper">
		<div id="header">D3Up</div>
		<ul id="navigation">
			<li><a href="/">Home</a></li>
			<li><a href="/item/create">Create Item</a></li>
			<li><a href="/build">All Builds</a></li>
			<li><a href="/user/builds">My Builds</a></li>
			<li><a href="/user/items">My Items</a></li>
			<? if($profile = Epic_Auth::getInstance()->getProfile()): ?>
				<!-- <li><a href="/user"><?= $profile->username ?></a></li>	 -->
				<li><a href="/user/logout">Logout</a></li>
			<? else: ?>
				<li><a href="/user/login">Login</a></li>
				<li><a href="/user/register">Register</a></li>
			<? endif; ?>
		</ul>
		<div id="sys-message" class="ui-widget ui-widget-content ui-corner-all">
			<b>System Message</b>: Update #6 - Created the "<a href="/build/">Builds</a>" page to browse all builds and you can now publish a guide to go with your build by visiting the "Guide" tab on your build, use it to explain how you play and how your build is used! For a full list of changes or to submit feedback/bugs/complains/praise/whatever, visit the post on <a href="http://www.reddit.com/r/Diablo/comments/vpetk/ready_for_testers_item_comparison_character/">/r/diablo</a>, or you can email me directly at <a href="mailto:aaron.cox@greymass.com">aaron.cox@greymass.com</a>.
		</div>
		<div id="main">
			<div id="content">
				<?= $this->layout()->content ?>
			</div>
		</div>
	</div>
	<script src="//static.getclicky.com/js" type="text/javascript"></script>
	<script type="text/javascript">try{ clicky.init(66607061); }catch(e){}</script>
	<noscript><p><img alt="Clicky" width="1" height="1" src="//in.getclicky.com/66607061ns.gif" /></p></noscript>
</body>
</html>