<!doctype html>
<head>
	<title>D3Up.com</title>
	<link rel="stylesheet" href="/css/style.css" type="text/css" charset="utf-8">	
	<link rel="stylesheet" href="/css/select2.css" type="text/css" charset="utf-8">	
	<link rel="stylesheet" href="/css/tooltip.css" type="text/css" charset="utf-8">	
	<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.js"></script>
	<script type="text/javascript" src="/js/select2.js"></script>
</head>
<body>
	<div id="wrapper">
		<div id="header">D3Up</div>
		<ul id="navigation">
			<li><a href="/">Home</a></li>
			<li><a href="/item/create">+Item</a></li>
			<li><a href="/hero/create">+Hero</a></li>
		</ul>
		<div id="main">
			<div id="content" class="inline-flow">
				<?= $this->layout()->content ?>
			</div>
			<div id="context" class="inline-flow">

			</div>
		</div>
	</div>
</body>
</html>