<tbody>
	<tr>
		<td colspan="10" class="build-paginator td-paginator button-bar">
			<?php
			  if($this->builds instanceOf Zend_Paginator) {
  			  echo $this->paginationControl($this->builds,
  			                                    'Elastic',
  			                                    'build/_pages.phtml',
  																					array(
  																						'class' => $this->class,
  																						'sortBy' => $this->sortBy,
  																						'selectedActives' => $this->selectedActives,
  																						'selectedPassives' => $this->selectedPassives,
																							'isHardcore' => $this->isHardcore,
  																					));
			  }
			?>
		</td>
	</tr>
	<tr>
		<?
			$params = "";
			if($this->class) {
				$params .= "&class=".$this->class;
			}
			if($this->selectedActives) {
				$params .= "&skills=".$this->selectedActives;
			}
			if($this->selectedPassives) {
				$params .= "&passives=".$this->selectedPassives;
			}
		?>
		<th></th>
		<th class="views">SC/HC</th>
		<th><a href="?sort=name<?= $params ?>">Name</a></th>
		<th>Skills</th>
		<th><a href="?sort=dps<?= $params ?>">DPS</a></th>
		<th><a href="?sort=ehp<?= $params ?>">EHP</a></th>
		<th></th>
	</tr>
<? foreach($this->group->members as $build): ?>
	<tr class='build-row'>
		<td class="icon"><img src="/images/<?= $build->class ?>.png"/></td>
		<td><?= ($build->hardcore) ? "<span class='neg' title='Hardcore'>HC</span>" : "<span class='pos' title='Softcore'>SC</span>" ?> </td>
		<td class='name'><?= $this->mLink($build) ?></td>
		<td class="skills">
			<? if($build->actives): ?>
				<? foreach($build->actives as $active): ?>
					<? 
						if($active == "undefined") {
							?>
							<img data-class="<?= $build->class ?>" src="/images/icons/unknown.png" class="skill-tip"/>
							<?
							continue;
						}
						$explode = explode("~", $active);
						$skill = $explode[0];
					?>
					<img data-class="<?= $build->class ?>" data-id="<?= $active ?>" data-class="<?= $build->class ?>" src="/images/icons/<?= $build->class ?>-<?= $skill ?>.png" class="skill-tip"/>
				<? endforeach ?>
			<? endif ?>
			<? if($build->passives): ?>
				<? foreach($build->passives as $passive): ?>
					<? 
						$explode = explode("~", $passive);
						$skill = $explode[0];
					?>
					<img data-class="<?= $build->class ?>" data-id="<?= $passive ?>" src="/images/icons/<?= $build->class ?>-<?= $skill ?>.png" class="skill-tip"/>
				<? endforeach ?>
			<? endif ?>
		</td>
		<td class="stat"><?= $this->prettyStat($build->stats['dps']) ?></td>
		<td class="stat"><?= $this->prettyStat($build->stats['ehp']) ?></td>
		<? if($this->myGroup): ?>
			<td class="stat"><a class='button' href="/group/<?= $this->group->id ?>/remove/build/<?= $build->id ?>">Remove</a></td>
		<? endif ?>
		<? if(!$this->myGroup && $this->profile->id == $build->_createdBy->id): ?>
			<td class="stat"><a class='button' href="/group/<?= $this->group->id ?>/leave/build/<?= $build->id ?>">Leave</a></td>
		<? endif ?>
	</tr>
<? endforeach; ?>
	<tr>
		<td colspan="10" class="build-paginator td-paginator button-bar">
			
			<?php
			  if($this->builds instanceOf Zend_Paginator) {
  			  echo $this->paginationControl($this->builds,
  			                                    'Elastic',
  			                                    'build/_pages.phtml',
  																					array(
  																						'class' => $this->class,
  																						'sortBy' => $this->sortBy,
  																						'selectedActives' => $this->selectedActives,
  																						'selectedPassives' => $this->selectedPassives,
																							'isHardcore' => $this->isHardcore,
  																					));
			  }
			?>
		</td>
	</tr>
</tbody>