<?
	$this->headTitle("Create a Group"); 
?>
<div id="build-create" class='content-page'>
	<div class='featured title-block' data-class="all">
		<h5 style='color: #B18135'>Create a Group</h5>
		<h2><a href="/build/create">Create a Group of Character Builds</a></h2>
		<div class='section-preview'>
			<p>A group on D3Up is a collection of builds either of your choice or whoever wants to join. You can specify whether the group is Closed (You add all builds) or Open (Anyone can join), then you can use that link to keep tabs of all your builds or your friends!</p>
		</div>
	</div>
	<div class="form">
		<?= $this->form ?>
	</div>
</div>