<?
	$this->headTitle("Create a Group"); 
?>
<div id="build-create" class='content-page'>
	<div class='featured title-block' data-class="all">
		<h5 style='color: #B18135'>Create a Group</h5>
		<h2><a href="/build/create">Create a Group of Character Builds</a></h2>
		<div class='section-preview'>
			<p>By creating a <strong>group</strong>, you will be able to add characters to it, creating a <strong>group</strong> of characters that can all be displayed on one page. Feel free to create a group for your group of friends, your clan/guild or even a group of your different characters to display on one page!</p>
		</div>
	</div>
	<div class="form">
		<?= $this->form ?>
	</div>
</div>