<?php $this->headTitle("Error"); ?>
<?php if ('development' == APPLICATION_ENV): ?> 
  <h2><?= $this->escape( get_class($this->exception) ); ?></h2>
  <b>Message:</b> <?= $this->exception->getMessage() ?> 
	<h3>Stack trace:</h3> 
	<ul class='errors'  style='overflow:scroll'>
	<?php foreach ($this->exception->getTrace() as $stack => $trace): ?>
	  <li>
	    <?php if (isset($trace['file']) && isset($trace['line'])): ?>
	      <a href='txmt://open?url=file://<?= $this->escape( $trace["file"] ); ?>&line=<?= $this->escape( $trace["line"] ); ?>'>[e]</a>          
	      <?= $this->escape( $trace["file"].":".$trace["line"] ); ?><br />
	    <?php endif ?>
	      <?php if (isset($trace["class"])): ?>
	        <?= $this->escape( $trace["class"].$trace["type"]); ?>
	      <?php endif ?>
	      <?= $this->escape( $trace["function"] ); ?>
	      <?php if (count($trace["args"])): ?>
	        (<?php foreach ($trace["args"] as $arg): ?>
	          ...
	          ,
	        <?php endforeach ?>)
	      <?php endif ?>
	      <?php if ('development' == $this->env): ?> 
	        <?php var_dump($trace); ?>
	      <?php endif; ?>
	    </li>
	<?php endforeach ?>
	</ul>
	<h3>Request Parameters:</h3> 
	<pre><? var_dump($this->request->getParams()) ?></pre>
<?php else: ?>
	<h1>Not found <span>:(</span></h1>
   <p>Sorry, but the page you were trying to view does not exist.</p>
   <p>It looks like this was the result of either:</p>
   <ul>
     <li>a mistyped address</li>
     <li>an out-of-date link</li>
   </ul>
   <script>
     var GOOG_FIXURL_LANG = (navigator.language || '').slice(0,2),GOOG_FIXURL_SITE = location.host;
   </script>
   <script src="http://linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"></script>
<?php endif ?>