<?php $this->headTitle("Error"); ?>
<?php if ('development' == APPLICATION_ENV): ?> 
  <h2><?= $this->escape( get_class($this->exception) ); ?></h2>
  <b>Message:</b> <?= $this->exception->getMessage() ?> 
	<h3>Stack trace:</h3> 
	<ul class='errors'  style='overflow:scroll'>
	<?php foreach ($this->exception->getTrace() as $stack => $trace): ?>
	  <li>
	    <?php if (isset($trace['file']) && isset($trace['line'])): ?>
	      <a href='txmt://open?url=file://<?= $this->escape( $trace["file"] ); ?>&line=<?= $this->escape( $trace["line"] ); ?>'>[e]</a>          
	      <?= $this->escape( $trace["file"].":".$trace["line"] ); ?><br />
	    <?php endif ?>
	      <?php if (isset($trace["class"])): ?>
	        <?= $this->escape( $trace["class"].$trace["type"]); ?>
	      <?php endif ?>
	      <?= $this->escape( $trace["function"] ); ?>
	      <?php if (count($trace["args"])): ?>
	        (<?php foreach ($trace["args"] as $arg): ?>
	          ...
	          ,
	        <?php endforeach ?>)
	      <?php endif ?>
	      <?php if ('development' == $this->env): ?> 
	        <?php var_dump($trace); ?>
	      <?php endif; ?>
	    </li>
	<?php endforeach ?>
	</ul>
	<h3>Request Parameters:</h3> 
	<pre><? var_dump($this->request->getParams()) ?></pre>
<?php else: ?>
	<div class="ui-widget ui-widget-content ui-corner-all" style="padding: 5px 20px">
	  <h2>Error #<?= rand(3007,3700) ?></h2>
	  <b>Message:</b> <?= $this->exception->getMessage() ?> 
	</div>
<?php endif ?>