<div class="d3up-post ui-widget ui-widget-content ui-corner-all" id="<?= $this->post->_type ?>-<?= $this->post->id ?>">
	<div class="meta"><?= $this->timeAgo($this->post->_created) ?></div>
	<h3><a href="/update/<?= $this->post->id ?>">Version <?= $this->post->version ?></a></h3>
	<div class="post-body">
		<?= $this->post->body ?>
	</div>
</div>
<div id="disqus_thread" style="margin-top: 50px"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'd3up'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>