<?
$uri = "http://".$_SERVER['HTTP_HOST']."/user/change-password?id=".$this->user->_id."&key=".$this->user->resetHash;
?>

<p>You have requested to reset your password on D3Up.com.</p>

<p>Please visit: <a href="<?= $uri ; ?>"><?=$uri?></a> where you will be asked to set a new password.</p>

<p>This link is only valid for (6) hours, after that, you will have to issue another password reset request.</p>


<p>Thanks!</p>

<p>- The Password Goblins</p>