<h3>My Heroes</h3>
<? if($this->notLoggedIn): ?>
	<p>This feature is only available to logged in users due to the nature of the application.</p>
	<p>When logged in, the database will save your characters as well as the gear you are wearing, allowing you to quickly compare items against your current gear. Detailed statistics about your character will also be generated allowing you to make informed decisions about gear changes without actually having to purchase the gear itself.</p>
	<p>Interested? Feel free to wander over to the <a href="/user/register">registration page</a> to create an account, or if you already have one, you can <a href="/user/login">login</a>.</p>
<? else: ?>
	<p><a href="/hero/create">Add Hero</a></p>
	<? if(count($this->heroes->export())):?>
	<ul>
		<? foreach($this->heroes as $hero): ?>
			<li><?= $this->mLink($hero) ?> (<?= ucwords(str_replace("-", " ", $hero->class)) ?>)</li>
		<? endforeach ?>
	</ul>
	<? else: ?>
	<p>You don't have any characters yet!</p>
	<p>Click the "Add Hero" button above to get started.</p>
	<? endif; ?>
<? endif; ?>