<? if($this->notLoggedIn): ?>
	<h1 class="table-header">My Shop</h1>
	<div class="user-shop">
		<ul>
			<li><a href="#tab-all-complete">All Completed Sales</a></li>
			<li><a href="#tab-help">What is this?</a></li>
		</ul>
		<div id="tab-all-complete">
			<?= $this->render("./user/shop/all-completed.phtml") ?>
		</div>
		<div id="tab-help">
			<?= $this->render("./user/shop/help.phtml") ?>
		</div>
	</div>
	<script type="text/javascript">
		$(function() {
			$(".user-shop").tabs();			
		});
	</script>
<? else: ?>
	<? if($this->form): ?>
	<div class="create-form ui-widget ui-widget-content ui-corner-all">
		<h3>Your shopping/selling preferences</h3>
		<?= $this->form ?>
	</div>
	<? else: ?>
		<?= $this->render("./user/_shop-interface.phtml") ?>
	<? endif; ?>
<? endif; ?>
<? if($this->selectItem): ?>
	<script type="text/javascript">
		$(function() {
			$("#item-picker").show();
		});
	</script>
<? endif ?>