<? if($this->notLoggedIn): ?>
	<h1 class="table-header">My Shop</h1>
	<div class="ui-widget ui-corner-all ui-widget-content ui-helper-clearfix" style="padding: 0 20px">
		<?= $this->render("./user/shop/help.phtml") ?>
	</div>
<? else: ?>
	<? if($this->form): ?>
	<div class="create-form ui-widget ui-widget-content ui-corner-all">
		<h3>Your shopping/selling preferences</h3>
		<?= $this->form ?>
	</div>
	<? else: ?>
		<?= $this->render("./user/_shop-interface.phtml") ?>
	<? endif; ?>
<? endif; ?>
<? if($this->selectItem): ?>
	<script type="text/javascript">
		$(function() {
			$("#item-picker").show();
		});
	</script>
<? endif ?>