<? if($this->notLoggedIn): ?>
	<p>This feature is only available to logged in users due to the nature of the application.</p>
	<p>A logged in user is allowed to flag his/her items for sale using this customer interface.</p>
	<p>Interested? Feel free to wander over to the <a href="/user/register">registration page</a> to create an account, or if you already have one, you can <a href="/user/login">login</a>.</p>
<? else: ?>
	<? if($this->form): ?>
	<div class="create-form ui-widget ui-widget-content ui-corner-all">
		<h3>Your shopping/selling preferences</h3>
		<?= $this->form ?>
	</div>
	<? else: ?>
		<?= $this->render("./user/_shop-interface.phtml") ?>
	<? endif; ?>
<? endif; ?>
<? if($this->selectItem): ?>
	<script type="text/javascript">
		$(function() {
			$("#item-picker").show();
		});
	</script>
<? endif ?>