<div class='ui-widget ui-widget-content ui-corner-all'>
	<h3>What is D3Up?</h3>
	<p>D3Up is designed as a tool to help you find information about Items, a place to create varies Character Builds, and compare your items to determine which stats will change.</p>
</div>
<div class='ui-widget ui-widget-content ui-corner-all'>
	<h3>What can I do here?</h3>
	<ul>
		<li><a href="/item/create">Create Items</a> to share with others or add to your builds.</li>
		<li>Create <a href="/build/create">Character Builds</a>, complete with gear, skills and detailed statistics!</li>
		<li>Compare the items in your build to other items you've created.</li>
	</ul>
</div>
