<div class='page'>
	<h3>Site Updates</h3>
	<? $posts = Epic_Mongo::db('update')->fetchAll(array(), array("_created" => -1), 5)?>
	<ul style="padding: 10px 0; margin: 0; list-style: none">
		<? foreach($posts as $p): ?>
			<li>
				<a href="/update/<?= $p->id ?>">V0.<?= $p->version ?></a>
				<span style="font-size: 11px">(<?= $this->timeAgo($p->_created)?>)</span>
			</li>
	<? endforeach ?>
	</ul>
</div>