<div class="home inline-flow">
	<?= $this->render("./post/_breadcrumb.phtml") ?>

	<? foreach($this->posts as $post): ?>
		<?= $this->partial("./post/types/".$post->_type.".phtml", array('post' => $post)) ?>
	<? endforeach; ?>

	<?php echo $this->paginationControl($this->posts,
	                                    'Elastic',
	                                    'index/_pages.phtml'); ?>
</div>
<div class="info inline-flow">
	<?= $this->render("./post/_sidebar.phtml")?>
</div>
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'd3up'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>