<h3 class="section-title"><?= $this->section->title ?></h3>
<? 
	parse_str( parse_url( $this->section->youtube, PHP_URL_QUERY ), $params );
	$id = $params['v'];
?>
<div class="section-specific youtube-video">
	<? if($this->section->youtube && $this->section->youtube != ""): ?>
		<iframe data-youtube="<?= $this->section->youtube ?>" width="900" height="506" src="http://www.youtube.com/embed/<?= $id ?>" frameborder="0" allowfullscreen></iframe>
	<? endif ?>
</div>
<div class="section-content">
	<?= $this->section->content ?>
</div>